// textes-en.js — the game text in English
//
// Traduction. Ce qui n'est PAS traduit, et ne le sera pas : noms de joueurs, de clubs,
// de villes, de sponsors, prénoms de coachs. Ce sont des noms propres.
//
// Chargé par un <script> CLASSIQUE, pas un module ES : ceux-ci sont bloqués par CORS sous
// file://, et le jeu doit pouvoir s'ouvrir par double-clic.
//
// Une clé peut porter une chaîne, ou { un, autres } quand un pluriel est en jeu. Le
// français met 0 ET 1 au singulier, l'anglais met 0 au pluriel : c'est `REGLE_PLURIEL` qui
// tranche, pas ce fichier.
//
// Les marqueurs {nom} sont substitués par `T(cle, params)`. L'échappement reste à
// l'appelant : `T('cle', { nom: escHtml(p.nom) })`.

// Pas de garde `typeof` autour de cette affectation : `TEXTES` est déclaré dans le bloc
// d'amorçage de la page, donc toujours là. Un garde ferait échouer le chargement EN SILENCE
// si l'ordre changeait un jour — et c'est exactement le défaut qu'on a payé une fois.
Object.assign(TEXTES.en, {
  "ecran.effectif.label": "Squad",
  "ecran.effectif.court": "Squad",
  "ecran.club.label": "Club",
  "ecran.club.court": "Club",
  "ecran.entrainement.label": "Training",
  "ecran.entrainement.court": "Train.",
  "ecran.classement.label": "Standings",
  "ecran.classement.court": "Table",
  "ecran.calendrier.label": "Fixtures",
  "ecran.calendrier.court": "Fixtures",
  "ecran.transferts.label": "Transfers",
  "ecran.transferts.court": "Transf.",
  "ecran.inbox.label": "Messages",
  "ecran.inbox.court": "Messages",
  "ecran.historique.label": "History",
  "ecran.historique.court": "History",
  "ecran.coupe.label": "Cup",
  "ecran.coupe.court": "Cup",
  "ecran.aide.label": "Help",
  "ecran.aide.court": "Help",
  "ecran.options.label": "Settings",
  "ecran.options.court": "Settings",
  "reglages.langue.titre": "Language",
  "reglages.langue.note": "The whole game follows this choice. Player, club and town names stay as they are — they are proper nouns.",
  "reglages.son.titre": "Sound",
  "reglages.son.note": "The music changes with the screen. It stops on its own when you leave the app.",
  "reglages.son.active": "On",
  "reglages.son.coupee": "Muted",
  "reglages.son.volume": "Volume",
  "reglages.partie.titre": "Current game",
  "reglages.partie.note": "Go back to the title screen to switch slot or start another game. Yours is saved automatically — you will find it exactly as you left it.",
  "reglages.partie.retour": "Back to title screen",
  "reglages.partie.confirmer": "Back to title",
  "reglages.partie.question": "Go back to the title screen?\\n\\nYour game is saved — you will find it in this slot.",
  "reglages.barre.titre": "Bottom bar",
  "reglages.barre.note": "Choose which screens appear directly, and in what order. The rest stay available under the « More » button.",
  "reglages.barre.retirer": "Remove {ecran} from the bar",
  "reglages.barre.ajouter": "Add {ecran} to the bar",
  "reglages.barre.capacite": {"un": "This screen shows <b>{n} entry</b> at its current width ({largeur} px).", "autres": "This screen shows <b>{n} entries</b> at its current width ({largeur} px)."},
  "reglages.barre.reste": {"un": "The last screen is under « More ».", "autres": "The other {n} screens are under « More »."},
  "reglages.barre.tout": "Everything fits in the bar, the « More » button disappears.",
  "reglages.barre.elargis": "Widen the window and the bar fills out by itself.",
  "reglages.version": "version {n}",

  // ---- tranche 2 : bandeau, bouton d'action, tiroir
  "bandeau.saison": "season",
  "bandeau.journee": "matchday",
  "bandeau.budget": "Budget",
  "bandeau.objectif": "Target",
  "bandeau.direction": "Board",
  "bandeau.rang": "{rang} of {total}",
  "nav.plus": "More",
  "action.journee": "Play matchday {n}",
  "action.coupe.tirage": "Draw the Coupe de France",
  "action.coupe.resultats": "Coupe de France results",
  "action.coupe.jouer": "Play the Coupe de France tie",
  "action.playoffs.lancer": "Start the playoffs (Top 8)",
  "action.playoffs.final": "See the final playoff result",
  "action.playoffs.quart": "Play a quarter-final",
  "action.playoffs.demi": "Play a semi-final",
  "action.playoffs.finale": "Play a final",
  "action.bilan": "End-of-season review",

  // ---- courrier
  "courrier.date": "Season {saison} · matchday {journee}",
  "courrier.ta-reponse": "Your answer: {dit}",
  "courrier.brut.titre": "{titreHtml}",
  "courrier.brut.corps": "{corpsHtml}",
  "courrier.brouille.deplace": "Your answer: {dit} {nom} moves to line {ligne}.",
  "courrier.brouille.impossible": "No line can take him. He stays where he is.",
  "courrier.vestiaire.partir.titre": "🚪 {nom} wants out",
  "courrier.vestiaire.tete.titre": "😠 {nom} is sulking",
  "courrier.vestiaire.partir.corps": {"un": "{portraitHtml}{nom} came to see me. He has had enough of this situation and asks to leave the club. {n} game played this season.", "autres": "{portraitHtml}{nom} came to see me. He has had enough of this situation and asks to leave the club. {n} games played this season."},
  "courrier.vestiaire.tete.corps": {"un": "{portraitHtml}{nom} is still fuming. {n} game played this season, and he reckons he is worth more than that.", "autres": "{portraitHtml}{nom} is still fuming. {n} games played this season, and he reckons he is worth more than that."},
  "courrier.engagement.tenu.titre": "🤝 Promise kept — {nom}",
  "courrier.engagement.rompu.titre": "💥 Promise broken — {nom}",
  "courrier.engagement.chiffre.tenu": "{nom} played {presences} of the last {journees} matchdays, as promised. He will not forget it.",
  "courrier.engagement.chiffre.rompu": "{nom} only played {presences} times out of {journees}. He had my word. He is asking to leave.",
  "courrier.engagement.parole.tenue": "{nom} is back at work. The talk got through.",
  "courrier.engagement.parole.rompue": "{nom} saw none of what I promised him. He will never believe me again.",
  "courrier.objectifJoueur.atteint.titre": "🎯 Personal target met",
  "courrier.objectifJoueur.manque.titre": "📉 Personal target missed",
  "courrier.objectifJoueur.atteint.corps": "{nom} met his target of {cible} goals ({buts} scored) — morale up.",
  "courrier.objectifJoueur.manque.corps": "{nom} only scored {buts} against a target of {cible} — a little disappointed.",
  "courrier.coupe.titre": "🏆 Coupe de France",
  "courrier.coupe.auto": "The cup was settled automatically before the playoffs began (winner: {vainqueur}).",
  "courrier.coupe.tirage.tard": "The draw is done: <b>{clubs} clubs entered</b>, from Régional to Élite — one per association, as the rules require. Your level means you enter later, when only {entree} teams are left. Seeded no. {tete}.",
  "courrier.coupe.tirage.premier": "The draw is done: <b>{clubs} clubs entered</b>, from Régional to Élite — one per association, as the rules require. You enter in the first round. Seeded no. {tete}.",
  "courrier.coupe.tirage.exempt": "The draw is done: <b>{clubs} clubs entered</b>, from Régional to Élite — one per association, as the rules require. You enter in the first round, and you have a bye. Seeded no. {tete}.",
  "courrier.coupe.fin.titre": "🏆 Coupe de France over",
  "courrier.coupe.fin.gagnee": "Your team wins the Coupe de France, against {equipes} teams entered! Prize: {prime}.",
  "courrier.coupe.fin.autre": "{nom} ({origine}) wins the Coupe de France this season.",
  "courrier.effectif.grave.titre": "🚨 The board is worried about the squad",
  "courrier.effectif.leger.titre": "📉 The board on the squad",
  "courrier.effectif.grave.corps": "A word on the group before the season starts. The squad averages <b>{force}</b>, while {division} sits around <b>{milieu}</b>: <b>{ecart} points behind</b>. At that gap, training alone will not save the season — it gains a few points a year, not ten. The <b>transfer market</b> is the only immediate lever: a few well-chosen signings beat a season of sessions.",
  "courrier.effectif.leger.corps": "A word on the group before the season starts. The squad averages <b>{force}</b>, while {division} sits around <b>{milieu}</b>: <b>{ecart} points behind</b>. Training can close that in a season or two with good staff. One or two signings would speed it up.",
  "courrier.stade.point.titre": "🏗️ The board on the facilities",
  "courrier.stade.point.corps": "A word before the season starts. {detailHtml} On the court, nothing stops us aiming higher — on paper, plenty does.",
  "courrier.stade.refus1.titre": "🚧 We have already been denied a promotion",
  "courrier.stade.refus1.corps": "Last season we won on the court and lost at the desk: promotion was <b>denied</b> for want of a rated venue. {detailHtml}{chiffrageHtml} Starting another season on these terms would mean playing for nothing.",
  "courrier.stade.refusN.titre": "🛑 {n} promotions denied — the venue is THE priority",
  "courrier.stade.refusN.corps": "<b>{n} times</b> we earned promotion on the court, <b>{n} times</b> it was denied for the same reason. {detailHtml}{chiffrageHtml} Until the venue is rated, every euro spent on the squad is money that will not get us up.",
  "courrier.stade.encore.titre": "🛑 Promotion will slip away again",
  "courrier.stade.insiste.titre": "⚠️ The board insists on the building work",
  "courrier.stade.encore.corps": {"un": "We are {rang}{ordinal} and promotion is taking shape. It would be <b>denied as things stand</b>. {detailHtml} That is exactly what has already happened to us {refus} times. {n} matchday left to act.", "autres": "We are {rang}{ordinal} and promotion is taking shape. It would be <b>denied as things stand</b>. {detailHtml} That is exactly what has already happened to us {refus} times. {n} matchdays left to act."},
  "courrier.stade.insiste.corps": "We are {rang}{ordinal} and promotion is taking shape. It would be <b>denied as things stand</b>. {detailHtml}",
  "courrier.stade.homologue.titre": "✅ Venue approved",
  "courrier.stade.homologue.corps": "The work has been signed off. Our venue is now <b>class {classe}</b>: it meets the requirements for {division}. Promotion now depends on results alone.",
  "courrier.objectif.fixe.titre": "📋 The board sets its target",
  "courrier.objectif.fixe.corps": "For this season in {division}, the board sets the target: {objectif}.",
  "courrier.objectif.atteint.titre": "✅ Target met",
  "courrier.objectif.manque.titre": "⚠️ Target missed",
  "courrier.objectif.atteint.corps": "The board is satisfied: target « {objectif} » met! Confidence bonus: {prime}.",
  "courrier.objectif.manque.corps": "The board is disappointed: target « {objectif} » not met (board confidence down: {confiance}/100).",
  "courrier.accession.decrochee.titre": "🎟️ Promotion play-off won",
  "courrier.accession.phase.titre": "🎟️ Promotion play-off",
  "courrier.accession.pasDeTicket": {"un": "{rang}<sup>th</sup> in the group: no ticket for the promotion play-off. Our league sends only <b>{n}</b> club, taken from the top four (art. 9.3 B). We must finish higher.", "autres": "{rang}<sup>th</sup> in the group: no ticket for the promotion play-off. Our league sends only <b>{n}</b> clubs, taken from the top four (art. 9.3 B). We must finish higher."},
  "courrier.accession.gagnee": "Promotion tournament won: <b>{place}<sup>th</sup></b> of the {places} national places. Nationale 3 next.",
  "courrier.accession.perdue": "We played the promotion tournament, but the place slips away: only <b>{places} places</b> are up for grabs in the whole country (art. 9.3 C). Winning your group is not enough — you must come through the tournament.",
  "courrier.carriere.titre": "🎽 End of a national career",
  "courrier.carriere.corps": "{portraitHtml}{nom} ({age}) is leaving the national league.{statsHtml} He fully intends to keep skating at regional level, more quietly. Thanks for everything!",
  "courrier.espoir.titre": "🌟 New prospect",
  "courrier.espoir.corps": "{portraitHtml}{nom} ({age}, {poste}) comes out of the academy and signs his first professional contract with the club.",
  "courrier.prolongation.titre": "Contract extended",
  "courrier.prolongation.corps": {"un": "{portraitHtml}{nom} has extended his contract by {n} season.", "autres": "{portraitHtml}{nom} has extended his contract by {n} seasons."},
  "courrier.finContrat.titre": "Contract over",
  "courrier.finContrat.corps": "{portraitHtml}{nom} has left the club, his contract having run out (free agent).",
  "courrier.retourPret.titre": "🔄 Back from loan",
  "courrier.retourPret.corps": "{nom} is back from his loan.",
  "courrier.pret.titre": "🔄 Loan",
  "courrier.pret.corps": "{nom} is loaned out for the rest of the season. He will be back in the off-season.",

  // ---- presse, vestiaire, événements
  "presse.accroche.elogieux.0": "📰 A statement",
  "presse.accroche.elogieux.1": "📰 Style and substance",
  "presse.accroche.elogieux.2": "📰 A masterclass",
  "presse.accroche.elogieux.3": "📰 Steamrollered",
  "presse.accroche.neutre.0": "📰 A win that counts",
  "presse.accroche.neutre.1": "📰 Job done",
  "presse.accroche.neutre.2": "📰 Within themselves",
  "presse.accroche.severe.0": "📰 A night to forget",
  "presse.accroche.severe.1": "📰 The fall",
  "presse.accroche.severe.2": "📰 Nothing worked",
  "presse.accroche.severe.3": "📰 A rude awakening awaits",
  "presse.corps.exploit": "<i>{journal}</i> — {nous} {mien}–{sien} {eux}. Nobody saw that result coming against the league leaders.",
  "presse.corps.contreperf": "<i>{journal}</i> — {nous} {mien}–{sien} {eux}. A defeat to the bottom club, hard to explain away.",
  "presse.corps.large": "<i>{journal}</i> — {nous} {mien}–{sien} {eux}. The margin says everything about the control on show.",
  "presse.corps.lourde": "<i>{journal}</i> — {nous} {mien}–{sien} {eux}. The scoreline is harsh, but it is not stolen.",
  "presse.corps.simple": "<i>{journal}</i> — {nous} {mien}–{sien} {eux}.",
  "presse.corps.exploit.triple": "<i>{journal}</i> — {nous} {mien}–{sien} {eux}. Nobody saw that result coming against the league leaders. <b>{triple}</b> helps himself to a hat-trick.",
  "presse.corps.contreperf.triple": "<i>{journal}</i> — {nous} {mien}–{sien} {eux}. A defeat to the bottom club, hard to explain away. <b>{triple}</b> still helps himself to a hat-trick.",
  "presse.corps.large.triple": "<i>{journal}</i> — {nous} {mien}–{sien} {eux}. The margin says everything about the control on show. <b>{triple}</b> helps himself to a hat-trick.",
  "presse.corps.lourde.triple": "<i>{journal}</i> — {nous} {mien}–{sien} {eux}. The scoreline is harsh, but it is not stolen. <b>{triple}</b> still helps himself to a hat-trick.",
  "presse.corps.simple.triple": "<i>{journal}</i> — {nous} {mien}–{sien} {eux}. <b>{triple}</b> helps himself to a hat-trick.",
  "reponse.presse.mesure.label": "Stay measured",
  "reponse.presse.mesure.dit": "“One win, nothing more. We are back at work tomorrow.”",
  "reponse.presse.feliciter.label": "Praise the group",
  "reponse.presse.feliciter.dit": "“They were immense. Tonight belongs to them.”",
  "reponse.presse.concentre.label": "Stay focused",
  "reponse.presse.concentre.dit": "“We take the points and move on. Nothing is settled.”",
  "reponse.presse.caractere.label": "Praise their character",
  "reponse.presse.caractere.dit": "“They did not panic. That is what I take from it.”",
  "reponse.presse.defendre.label": "Defend my players",
  "reponse.presse.defendre.dit": "“Nobody hid out there. The group is not the problem.”",
  "reponse.presse.assumer.label": "Take the blame publicly",
  "reponse.presse.assumer.dit": "“That was unworthy of this club. Starting with me.”",
  "reponse.vestiaire.rassurer.label": "Reassure him",
  "reponse.vestiaire.rassurer.dit": "“You matter to this group. Keep a cool head.”",
  "reponse.vestiaire.promettre.label": "Promise him game time",
  "reponse.vestiaire.promettre.dit": "“You will play. I am telling you to your face, not into thin air.”",
  "reponse.vestiaire.ignorer.label": "Say nothing",
  "reponse.vestiaire.ignorer.dit": "“…”",
  "reponse.brouille.separer.label": "Split their lines",
  "reponse.brouille.separer.dit": "“They will not play together again.”",
  "reponse.brouille.laisser.label": "Let them sort it out",
  "reponse.brouille.laisser.dit": "“They are adults. Let them talk.”",
  "evenement.accrochage.titre": "🔥 Row in the changing room",
  "evenement.accrochage.corps": "{a} and {b} had words after the game. They play on the same line, and it shows now.",
  "evenement.parrainage.titre": "🧭 {ancien} takes {jeune} under his wing",
  "evenement.parrainage.corps": "The veteran spent the week working with the youngster. It will show on the court, and it already shows in the changing room.",
  "evenement.jalousie.titre": "😤 {frustre} is struggling with the competition",
  "evenement.jalousie.corps": "He reckons he is worth more than {rival}, who plays in his place. The mood between them is suffering.",
  "evenement.soiree.titre": "🎉 Club night",
  "evenement.soiree.corps": "Everyone was there — players, volunteers and committee. Nights like these are what hold a group together over a season.",

  // ---- écran Effectif, cartes et tableau
  "stat.general": "Overall",
  "stat.tir": "Shot",
  "stat.def": "Def",
  "stat.vit": "Speed",
  "stat.gar": "Keeper",
  "stat.agr": "Agg",
  "stat.forme": "Fitness",
  "stat.moral": "Morale",
  "stat.potentiel": "Potential",
  "stat.potentiel.estime": "Estimated potential",
  "stat.tir.court": "SHT",
  "stat.def.court": "DEF",
  "stat.vit.court": "SPD",
  "stat.gar.court": "GK",
  "colonne.pos": "Pos",
  "colonne.nom": "Name",
  "colonne.age": "Age",
  "colonne.contrat": "Contract",
  "colonne.valeur": "Value",
  "colonne.joueur": "Player",
  "colonne.matchs": "Games",
  "colonne.buts": "Goals",
  "colonne.penalites": "Penalties",
  "colonne.nomClub": "Name (club)",
  "joueur.indisponible": "out",
  "joueur.indisponible.semaines": {"un": "out {n}d", "autres": "out {n}d"},
  "joueur.contrat.ans": {"un": "{n} year", "autres": "{n} years"},
  "effectif.nbJoueurs": {"un": "{n} player", "autres": "{n} players"},
  "effectif.composition": "Line-up: <b>1 keeper</b> (no rotation) + <b>{n} outfield player(s)</b> rotating (●) — from <b>4</b> (one line) to <b>{max}</b> (three lines). One line: your best four on the court, but they burn out — <b>9 fitness points a matchday</b>. Two lines: <b>4.5</b>. Three lines: <b>3</b>, and everyone plays — at the cost of a lower average level, and a far calmer changing room.",
  "effectif.compoAuto": "Auto line-up",
  "effectif.intervalle": "Line change interval:",
  "effectif.intervalle.info": "more frequent changes = fresher players, longer shifts = more wear per stint",
  "effectif.minutes": {"un": "{n} minute", "autres": "{n} minutes"},
  "effectif.minutes1demi": "1.5 minutes",
  "effectif.masseSalariale": "Wage bill: {montantHtml}/game.",
  "effectif.selection": "Starting line-up",
  "effectif.selection.info": "Tap a card to select or drop a player (● = starter, outlined in green).",
  "effectif.consignes": "Tactical instructions",
  "effectif.consignes.info": "These instructions apply to every game (including live matches, where you can change them mid-game).",
  "effectif.style": "Style:",
  "effectif.pressing": "Pressing:",
  "effectif.objectifs": "Personal targets for the season",
  "effectif.objectifLigne": "{nom} — target: {cible} goals this season ({buts} scored)",
  "effectif.objectifAtteint": "met",
  "effectif.stats": "Season statistics",
  "effectif.complet": "Full squad (details, sale, loan)",
  "effectif.vendre": "Sell",
  "effectif.preter": "Loan out",
  "effectif.calmer": "Calm down",
  "effectif.sousConsigne": "Under orders",
  "effectif.calmer.info": "Fewer stick fouls, but plays deeper",
  "tactique.offensif": "Attacking (+attack, −defence)",
  "tactique.equilibre": "Balanced",
  "tactique.defensif": "Defensive (+defence, −attack)",
  "pressing.haut": "High (aggressive, more penalties)",
  "pressing.moyen": "Medium",
  "pressing.bas": "Low (cautious, fewer penalties)",

  // ---- Classement, Calendrier, Entraînement, staff
  "staff.attaque.label": "Attack coach",
  "staff.attaque.desc": "Improves the Shot of outfield players",
  "staff.defense.label": "Defence coach",
  "staff.defense.desc": "Improves the Defence of outfield players",
  "staff.physique.label": "Fitness coach",
  "staff.physique.desc": "Improves the Speed of the whole squad",
  "staff.gardiens.label": "Goalkeeping coach",
  "staff.gardiens.desc": "Improves the Keeper rating of goalkeepers",
  "staff.discipline.label": "Mental / discipline coach",
  "staff.discipline.desc": "Lowers player Aggression and cuts penalties in games",
  "staff.medecin.label": "Club doctor",
  "staff.medecin.desc": "Reduces the risk and length of injuries",
  "staff.recruteur.label": "Scout",
  "staff.recruteur.desc": "Cuts transfer costs and widens the recruitment pool beyond the division",
  "staff.specialistes.label": "Special teams coach",
  "staff.specialistes.desc": "Improves power-play efficiency and firms up the penalty kill",
  "staff.requis": "Requires: {quoi}",
  "staff.requis.division": "playing at least in {division}",
  "staff.requis.centre": "training centre level {n}",
  "staff.note": "rating <b>{n}</b>/95",
  "staff.noteCourte": "rating <b>{n}</b>",
  "staff.former": "Train (+1) — {prix}",
  "staff.maximum": "Maximum skill",
  "staff.licencier": "Dismiss ({prix})",
  "staff.vacant": "Post vacant",
  "staff.remplacer": "Replace — {prix}",
  "staff.embaucher": "Hire — {prix}",
  "staff.frequence": "The coach rating sets how often players improve.",
  "staff.mercato": "Coaching market:",
  "staff.mercato.avec": "Coaching market (replacing includes the severance payment):",
  "entrainement.dispo": "A session is available",
  "entrainement.deja": "Session already held this week",
  "entrainement.lancer": "Start the session",
  "entrainement.info": "An extra session, outside matchdays, mostly benefits the <b>rested line</b> (players left out) — they turn up fresh and can focus on technical work. Only one session between two matchdays.",
  "entrainement.staff": "Coaching staff",
  "entrainement.staff.info": "Hire your coaches on the <b>market</b> (rating = performance): young players and starters improve faster. Some posts unlock gradually (division + training centre level). You can <b>replace</b> a coach in post with a better one directly (the severance is included in the price), or <b>train</b> your current coach to raise his skill. The discipline coach also cuts penalties in games.",
  "entrainement.derniereSeance": "Last session:",
  "entrainement.derniereHorsMatch": "Last non-matchday session:",
  "entrainement.aucune": "No improvement on the last matchday.",
  "entrainement.aucune.sansCoach": "No improvement on the last matchday — hire a coach to get started!",
  "colonne.equipe": "Team",
  "colonne.poule": "Group",
  "colonne.pts": "Pts",
  "colonne.j": "P",
  "colonne.v": "W",
  "colonne.vp": "OTW",
  "colonne.dp": "OTL",
  "colonne.d": "L",
  "colonne.bp": "GF",
  "colonne.bc": "GA",
  "colonne.diff": "GD",
  "classement.sousTitre": "Matchday {journee} of {total} · {equipes} teams",
  "classement.prochaine": "Next fixture",
  "classement.rang": "{n}<sup>th</sup>",
  "classement.points": "{n} pts",
  "classement.domicile": "at home",
  "classement.exterieur": "away",
  "classement.journeeCourte": "MD{n}",
  "classement.detail": "Full figures and playoff rules",
  "classement.national": "{division} national table",
  "classement.national.detail": "{equipes} teams, {poules} groups",
  "classement.regle.poules": "Each group qualifies its top {n}. The final bracket brings together eight teams from across the division: group champions first, then the best of the rest.",
  "classement.regle.simple": "The top {n} go through to the playoffs.",
  "classement.regle.format": "Quarter-finals, semi-finals then the final, each round best of 3 (home, away, decider if needed). Both finalists go up.",
  "classement.playoffsAVenir": "The top {n} in the table will play the playoffs at the end of the regular season, each round a home-and-away series plus a decider if needed (best of 3).",
  "playoffs.titre": "Playoffs — {division} (Top {n}, best-of-3 series)",
  "playoffs.quarts": "Quarters",
  "playoffs.demies": "Semis",
  "playoffs.finale": "Final",
  "playoffs.aDeterminer": "to be decided",
  "playoffs.elimine": "Your team is out — the rest of the bracket is settled automatically when you press the action button.",
  "calendrier.sousTitre": "{n} matchdays · home and away",
  "calendrier.journee": "Matchday {n}",
  "calendrier.aller": "(home leg)",
  "calendrier.retour": "(away leg)",
  "calendrier.aVenir": "up next",
  "calendrier.avantMatch": "Pre-match — Next opponent ({ou})",
  "calendrier.bilan": "{v}W {n}D {d}L, form {forme}% of points taken",
  "calendrier.meilleur": "Best player: {qui}",
  "calendrier.danger": "Attacking threat: {qui}",

  // ---- Club et Transferts
  "club.niveau": "Level {n}/{max}",
  "club.niveauMax": "Maximum level",
  "club.niveauRequis": "Level {n} requires {division}",
  "club.ameliorer": "Upgrade — {prix}",
  "club.classe.titre": "Venue rating — class {classe}",
  "club.classe.regle": "Federal rules (art. 2.2.7.2) tie each division to a venue class.",
  "club.classe.suffisant": "Your level {niveau} venue is rated <b>{classe}</b>: it already allows promotion to {division}.",
  "club.classe.insuffisant": "Going up to {division} requires <b>class {classe}</b>, meaning a level {requis} venue. Yours is level {niveau}: without building work, promotion will be denied.",
  "club.classe.sommet": "You are at the top: class A is required for Élite and for any national final.",
  "club.sousTitre": "Capacity {places} seats · {n} project(s) available",
  "club.capacite": "Current capacity: {placesHtml} seats.",
  "club.chantiers": "Projects available this season: {chantiersHtml} (infrastructure upgrades and VIP boxes combined — building takes time, you cannot redo everything in one season).",
  "club.sponsor.actif": "Contract active",
  "club.sponsor.resilier": "Terminate",
  "club.sponsor.signer": "Sign",
  "club.recettes.domicile": "Last game revenue ({n} spectators)",
  "club.recettes.deplacement": "Last game revenue (away)",
  "club.poste.billetterie": "Ticketing",
  "club.poste.buvette": "Refreshments",
  "club.poste.loges": "VIP boxes",
  "club.poste.sponsoring": "Sponsorship",
  "club.poste.tv": "Broadcast rights",
  "club.poste.communication": "Marketing",
  "club.poste.salaires": "Wage bill (players)",
  "club.poste.staff": "Staff wages",
  "club.poste.entretien": "Upkeep / overheads",
  "club.poste.total": "Total",
  "club.aucuneRecette": "No revenue recorded yet.",
  "club.billetterie": "Ticketing & Marketing",
  "club.prixBillet": "Ticket price:",
  "club.prixBillet.info": "low price = bigger crowd, high price = more revenue per head",
  "club.communication": "Marketing budget (per home game):",
  "club.communication.info": "brings more people in, but costs at every home game",
  "club.sponsoring": "Sponsorship",
  "club.sponsoring.info": "Contracts are <b>cumulative</b>: you can sign several sponsors at once, each unlocked by a high enough division and facility level. Total income from active sponsors: {totalHtml}.",
  "club.finances": "Last game finances",
  "infra.stade.label": "Stands",
  "infra.stade.desc": "Increases how many spectators you can host",
  "infra.confort.label": "Comfort",
  "infra.confort.desc": "Seating and sightlines: brings spectators back",
  "infra.buvette.label": "Refreshments",
  "infra.buvette.desc": "Increases average spend per spectator",
  "infra.centre.label": "Training centre",
  "infra.centre.desc": "Speeds up every improvement from the coaching staff",
  "infra.pole.label": "Academy",
  "infra.pole.desc": "Regularly develops high-potential youngsters who join the squad directly — partly offsetting retirements",
  "infra.loges.label": "VIP boxes",
  "infra.loges.compte": {"un": "{n}/15 box", "autres": "{n}/15 boxes"},
  "infra.loges.recette": "{montant}/game in fixed income",
  "infra.loges.requis": "Box {n} requires {division}",
  "infra.loges.construire": "Build a box — {prix}",
  "poste.tous": "All positions",
  "poste.G": "Goalkeeper",
  "poste.D": "Defender",
  "poste.A": "Forward",
  "tri.ov": "Overall",
  "tri.tir": "Shot",
  "tri.def": "Def",
  "tri.vit": "Speed",
  "tri.gar": "Keeper",
  "tri.val": "Value",
  "tri.age": "Age",
  "tri.agr": "Aggression",
  "transferts.sousTitre": "Budget {budget} · {n} players under contract",
  "transferts.ferme": "The transfer market only opens from <b>season 2</b>.",
  "transferts.ferme.info": "Your first season is played with the starting squad — prove yourself, see who improves, and build your budget before entering the market.",
  "transferts.titre": "Recruitment centre",
  "transferts.info": "Budget available: {budgetHtml}. Buying = value +10% (± premium outside the division). Selling (Squad tab) = value −10%. A club may refuse to sell or counter with a higher price — a good <b>scout</b> limits that risk and lowers the price.<br>The badge next to the overall rating shows what the signing <b>adds</b>: the gap with the player in his position he would replace, that is the weakest in the group.<br>Below the value is his <b>wage per matchday</b> — the transfer fee is a one-off, the wage is paid every game for the whole contract.",
  "transferts.portee": "Scope:",
  "transferts.portee.division": "My division ({division})",
  "transferts.portee.pyramide": "The whole pyramid (outside the division)",
  "transferts.poste": "Position:",
  "transferts.trier": "Sort by:",
  "transferts.decroissant": "Descending",
  "transferts.croissant": "Ascending",
  "transferts.acheter": "Buy {prix}",
  "transferts.recruter": "Sign {prix}",
  "transferts.nonVendable": "not for sale",
  "transferts.aucun": "No player matches this filter.",

  // ---- rapport de match, sous-menu, objectifs
  "objectif.milieu": "Aim for mid-table",
  "objectif.titre": "Aim for the playoff title",
  "objectif.playoffs": "Reach the playoffs (Top 8)",
  "objectif.maintien": "Stay up",
  "objectif.maintienDescente": "Stay up (avoid relegation)",
  "rapport.titre": "Matchday {n} — Match report",
  "rapport.prolongation": "Level at the end of regulation — golden goal in overtime.",
  "rapport.autres": "Other results:",
  "rapport.recette": "Game revenue: {montantHtml} (details in the Club tab)",
  "rapport.aucunePenalite": "No penalties called.",
  "rapport.aucunBut": "No goals…",
  "intro.objectif": "The board's target for this season: {objectifHtml}.",

  // ---- fautes, coupe, palmarès, messages
  "faute.retenir": "holding",
  "faute.accrocher": "hooking",
  "faute.trebucher": "tripping",
  "faute.obstruction": "interference",
  "faute.cinglage": "slashing",
  "faute.crosseHaute": "high stick",
  "faute.piquage": "spearing",
  "faute.retardJeu": "delay of game",
  "faute.surnombre": "too many players",
  "faute.chargeViolente": "charging",
  "faute.dureteExcessive": "roughing",
  "faute.chargeBalustrade": "boarding",
  "faute.chargeCrosse": "cross-checking",
  "faute.cinglageBlessure": "slashing causing injury",
  "faute.antisportive": "unsportsmanlike conduct",
  "faute.contestation": "dissent",
  "faute.conduiteAntisportive": "misconduct",
  "faute.blessureIntentionnelle": "intent to injure",
  "faute.agression": "physical assault",
  "faute.coupCrosseTete": "dangerous stick blow to the head",
  "penalite.mineure": "Minor penalty",
  "penalite.majeure": "Major penalty",
  "penalite.mec": "Misconduct penalty (no shorthanded play, player replaced)",
  "penalite.pm": "Match penalty — sent off",
  "penalite.inferiorite": "{n}' shorthanded.",
  "coupe.nom": "Coupe de France",
  "coupe.tour.finale": "Final",
  "coupe.tour.demi": "Semi-final",
  "coupe.tour.quart": "Quarter-final",
  "coupe.tour.seizieme": "Round of 32",
  "coupe.tour.trentedeuxieme": "Round of 64",
  "coupe.tour.preliminaire": "Preliminary round",
  "coupe.presentation": "A knockout competition featuring <b>every team from every national division</b>, from N3 to Élite — your whole division (its real standings this season), plus the others generated for the occasion. The top seeds get a bye in the preliminary round. No draws possible.",
  "coupe.rythme": "Rounds unlock gradually across the league matchdays — the cup always finishes well before the playoff semi-finals.",
  "coupe.tirageVerrouille": "The draw becomes available from matchday {journee} (currently matchday {actuelle}).",
  "coupe.lancerTirage": "Make the draw",
  "coupe.aJouer": "to play",
  "coupe.prolongationCourte": "(OT)",
  "coupe.exemptes": "Seeds with a bye in the preliminary round:",
  "coupe.enCours": "in progress",
  "coupe.engagees": "{n} teams entered, from N3 to Élite.",
  "coupe.vainqueur": "Winner:",
  "coupe.resultatFinal": "See the final result",
  "coupe.tourVerrouille": "The next round becomes available from matchday {journee} (currently matchday {actuelle}).",
  "coupe.jouerProchain": "Play the next tie",
  "palmares.montee": "Promoted",
  "palmares.descente": "Relegated",
  "palmares.maintien": "Stayed up",
  "palmares.champion": "champions",
  "palmares.finaliste": "runners-up",
  "palmares.saisons": {"un": "{n} season", "autres": "{n} seasons"},
  "palmares.montees": {"un": "{n} promotion", "autres": "{n} promotions"},
  "palmares.saisonEnCours": "Season {n} under way",
  "palmares.vide.titre": "Your first season is under way",
  "palmares.vide.note": "The honours list fills up at the end of each season. Here is what will go in it.",
  "palmares.vide.classement": "<b>Final position</b> — where you finished in the regular season",
  "palmares.vide.playoffs": "<b>Playoffs</b> — how far you went",
  "palmares.vide.mouvement": "<b>Movement</b> — promoted, stayed up or relegated",
  "palmares.vide.buteur": "<b>Top scorer</b> — the one who carried the season",
  "messages.compte": {"un": "{n} message", "autres": "{n} messages"},
  "messages.nonLus": {"un": "{n} unread", "autres": "{n} unread"},
  "messages.boiteVide": "Inbox empty",
  "messages.vide.titre": "No messages yet",
  "messages.vide.note": "The board, the staff and other clubs will write to you as the season goes on.",
  "messages.vide.objectifs": "<b>Targets</b> — what the board expects of you",
  "messages.vide.blessures": "<b>Injuries</b> — who is out, and for how long",
  "messages.vide.contrats": "<b>Contracts</b> — expiries to plan for",
  "messages.vide.sponsors": "<b>Sponsors</b> — the offers that unlock",

  // ---- tutoriel guidé
  "tuto.passer": "Skip the tutorial",
  "tuto.continuer": "Continue",
  "tuto.commencer": "Start",
  "tuto.compris": "Got it",
  "tuto.terminer": "Finish",
  "tuto.aller": "Tap <b>{ecran}</b>.",
  "tuto.tour.titre": "A quick look around",
  "tuto.tour.texte": "I will walk you through the screens one by one, up to your first game. It is short, and you can skip whenever you like.",
  "tuto.effectif.texte": "You are already here: this is your team sheet. You pick your keeper and your outfield players, and you see who is in form.",
  "tuto.composer.titre": "Picking your team",
  "tuto.composer.texte": "One keeper and four outfield players on the court, as roller in line hockey demands. The others rotate: the more you rotate, the less your players wear down.",
  "tuto.entrainement.texte": "Tap <b>{ecran}</b>. This is where your squad improves — or stalls, if you have nobody to coach them.",
  "tuto.coach.titre": "Your first coach",
  "tuto.coach.texte": "Hire a coach. With no staff, <b>nobody improves</b>: the session is even refused. I am showing you the cheapest, but you can pick another.",
  "tuto.seance.titre": "The first session",
  "tuto.seance.texte": "Run the session. One a week, between matchdays — it mostly benefits the players <b>left out</b>, who turn up fresh.",
  "tuto.lireClassement.titre": "Reading the table",
  "tuto.lireClassement.texte": "FFRS scale: <b>3</b> points for a win, <b>2</b> for an overtime win, <b>1</b> for an overtime loss, <b>0</b> for a defeat. Level on points, goal difference decides.",
  "tuto.construire.titre": "Building your club",
  "tuto.construire.texte": "Stands, comfort, refreshments, training centre, sponsors. Careful: <b>going up a division requires a rated venue</b> — without the building work, promotion is denied even if you win. Two projects a season, no more.",
  "tuto.reste.titre": "Everything else",
  "tuto.reste.tiroir": "Tap <b>{plus}</b>: transfers, fixtures, Coupe de France, messages, history, help and settings are kept there.",
  "tuto.reste.large": "Your screen is wide: every screen fits in the bar — transfers, fixtures, Coupe de France, messages, history, help and settings. On a phone, the last ones move into a « More » drawer.",
  "tuto.tiroir.titre": "Close the drawer",
  "tuto.tiroir.texte": "Close the drawer: pull the handle down, or tap anywhere above the panel.",
  "tuto.jouer.titre": "Off you go",
  "tuto.jouer.texte": "Tap <b>{bouton}</b>. You can watch the game unfold, or go straight to the result.",
  "tuto.fin.titre": "Over to you!",
  "tuto.fin.texte": "You have everything you need: pick, train, build, recruit. Start in Régional and climb as high as you can — Élite is five divisions up."
});

if (typeof PIECES_CHARGEES === 'object') PIECES_CHARGEES.textesen = true;
