// textes-fr.js — les textes du jeu en français
//
// Langue d'origine du jeu, et langue de repli de toutes les autres : quand une clé
// manque ailleurs, `T()` revient ici plutôt que de laisser un trou blanc.
//
// Chargé par un <script> CLASSIQUE, pas un module ES : ceux-ci sont bloqués par CORS sous
// file://, et le jeu doit pouvoir s'ouvrir par double-clic.
//
// Une clé peut porter une chaîne, ou { un, autres } quand un pluriel est en jeu. Le
// français met 0 ET 1 au singulier, l'anglais met 0 au pluriel : c'est `REGLE_PLURIEL` qui
// tranche, pas ce fichier.
//
// Les marqueurs {nom} sont substitués par `T(cle, params)`. L'échappement reste à
// l'appelant : `T('cle', { nom: escHtml(p.nom) })`.

// Pas de garde `typeof` autour de cette affectation : `TEXTES` est déclaré dans le bloc
// d'amorçage de la page, donc toujours là. Un garde ferait échouer le chargement EN SILENCE
// si l'ordre changeait un jour — et c'est exactement le défaut qu'on a payé une fois.
Object.assign(TEXTES.fr, {
  "ecran.effectif.label": "Effectif",
  "ecran.effectif.court": "Effectif",
  "ecran.club.label": "Club",
  "ecran.club.court": "Club",
  "ecran.entrainement.label": "Entraînement",
  "ecran.entrainement.court": "Entraîn.",
  "ecran.classement.label": "Classement",
  "ecran.classement.court": "Classem.",
  "ecran.calendrier.label": "Calendrier",
  "ecran.calendrier.court": "Calend.",
  "ecran.transferts.label": "Transferts",
  "ecran.transferts.court": "Transf.",
  "ecran.inbox.label": "Messages",
  "ecran.inbox.court": "Messages",
  "ecran.historique.label": "Historique",
  "ecran.historique.court": "Histor.",
  "ecran.coupe.label": "Coupe",
  "ecran.coupe.court": "Coupe",
  "ecran.aide.label": "Aide",
  "ecran.aide.court": "Aide",
  "ecran.options.label": "Réglages",
  "ecran.options.court": "Réglages",
  "reglages.langue.titre": "Langue",
  "reglages.langue.note": "Le jeu tout entier suit ce choix. Les noms de joueurs, de clubs et de villes ne changent pas — ce sont des noms propres.",
  "reglages.son.titre": "Son",
  "reglages.son.note": "La musique change selon l'écran. Elle se coupe toute seule quand tu quittes l'application.",
  "reglages.son.active": "Activée",
  "reglages.son.coupee": "Coupée",
  "reglages.son.volume": "Volume",
  "reglages.partie.titre": "Partie en cours",
  "reglages.partie.note": "Reviens à l'écran titre pour changer d'emplacement ou démarrer une autre partie. La tienne est sauvegardée automatiquement, tu la retrouveras telle quelle.",
  "reglages.partie.retour": "Retour à l'écran titre",
  "reglages.partie.confirmer": "Revenir au titre",
  "reglages.partie.question": "Revenir à l'écran titre ?\\n\\nTa partie est sauvegardée, tu la retrouveras à cet emplacement.",
  "reglages.barre.titre": "Barre du bas",
  "reglages.barre.note": "Choisis les écrans qui apparaissent directement, et leur ordre. Les autres restent accessibles par le bouton « Plus ».",
  "reglages.barre.retirer": "Retirer {ecran} de la barre",
  "reglages.barre.ajouter": "Ajouter {ecran} à la barre",
  "reglages.barre.capacite": {"un": "Cet écran affiche <b>{n} entrée</b> à sa largeur actuelle ({largeur} px).", "autres": "Cet écran affiche <b>{n} entrées</b> à sa largeur actuelle ({largeur} px)."},
  "reglages.barre.reste": {"un": "Le dernier écran est dans « Plus ».", "autres": "Les {n} écrans restants sont dans « Plus »."},
  "reglages.barre.tout": "Tout tient dans la barre, le bouton « Plus » disparaît.",
  "reglages.barre.elargis": "Élargis la fenêtre et la barre s'étoffe d'elle-même.",
  "reglages.version": "version {n}",

  // ---- tranche 2 : bandeau, bouton d'action, tiroir
  "bandeau.saison": "saison",
  "bandeau.journee": "journée",
  "bandeau.budget": "Budget",
  "bandeau.objectif": "Objectif",
  "bandeau.direction": "Direction",
  "bandeau.rang": "{rang}e/{total}",
  "nav.plus": "Plus",
  "action.journee": "Jouer la journée {n}",
  "action.coupe.tirage": "Lancer le tirage de la Coupe de France",
  "action.coupe.resultats": "Résultats de la Coupe de France",
  "action.coupe.jouer": "Jouer le match de Coupe de France",
  "action.playoffs.lancer": "Lancer les playoffs (Top 8)",
  "action.playoffs.final": "Voir le résultat final des playoffs",
  "action.playoffs.quart": "Jouer un match de quart de finale",
  "action.playoffs.demi": "Jouer un match de demi-finale",
  "action.playoffs.finale": "Jouer un match de la finale",
  "action.bilan": "Bilan de fin de saison",

  // ---- courrier
  "courrier.date": "Saison {saison} · journée {journee}",
  "courrier.ta-reponse": "Ta réponse : {dit}",
  "courrier.brut.titre": "{titreHtml}",
  "courrier.brut.corps": "{corpsHtml}",
  "courrier.brouille.deplace": "Ta réponse : {dit} {nom} passe en ligne {ligne}.",
  "courrier.brouille.impossible": "Aucune ligne ne peut l'accueillir. Il reste où il est.",
  "courrier.vestiaire.partir.titre": "🚪 {nom} veut partir",
  "courrier.vestiaire.tete.titre": "😠 {nom} fait la tête",
  "courrier.vestiaire.partir.corps": {"un": "{portraitHtml}{nom} est venu me voir. Il ne veut plus de cette situation et demande à quitter le club. {n} match joué cette saison.", "autres": "{portraitHtml}{nom} est venu me voir. Il ne veut plus de cette situation et demande à quitter le club. {n} matchs joués cette saison."},
  "courrier.vestiaire.tete.corps": {"un": "{portraitHtml}{nom} ne décolère pas. {n} match joué cette saison, et il estime valoir mieux que ça.", "autres": "{portraitHtml}{nom} ne décolère pas. {n} matchs joués cette saison, et il estime valoir mieux que ça."},
  "courrier.engagement.tenu.titre": "🤝 Parole tenue — {nom}",
  "courrier.engagement.rompu.titre": "💥 Parole non tenue — {nom}",
  "courrier.engagement.chiffre.tenu": "{nom} a joué {presences} des {journees} dernières journées, comme promis. Il ne l'oubliera pas.",
  "courrier.engagement.chiffre.rompu": "{nom} n'a joué que {presences} fois sur {journees}. Il avait ma parole. Il demande à partir.",
  "courrier.engagement.parole.tenue": "{nom} s'est remis au travail. Le discours a porté.",
  "courrier.engagement.parole.rompue": "{nom} n'a rien vu venir de ce que je lui avais dit. Il ne me croira plus.",
  "courrier.objectifJoueur.atteint.titre": "🎯 Objectif individuel atteint",
  "courrier.objectifJoueur.manque.titre": "📉 Objectif individuel manqué",
  "courrier.objectifJoueur.atteint.corps": "{nom} a atteint son objectif de {cible} buts ({buts} inscrits) — moral en hausse.",
  "courrier.objectifJoueur.manque.corps": "{nom} n'a marqué que {buts} but(s) sur un objectif de {cible} — un peu déçu.",
  "courrier.coupe.titre": "🏆 Coupe de France",
  "courrier.coupe.auto": "La coupe a été résolue automatiquement avant le coup d'envoi des playoffs (vainqueur : {vainqueur}).",
  "courrier.coupe.tirage.tard": "Tirage au sort effectué : <b>{clubs} clubs engagés</b>, du Régional à l'Élite — un par association, comme le veut le règlement. Ton niveau te fait entrer plus tard, quand il ne restera que {entree} équipes. Tête de série n°{tete}.",
  "courrier.coupe.tirage.premier": "Tirage au sort effectué : <b>{clubs} clubs engagés</b>, du Régional à l'Élite — un par association, comme le veut le règlement. Tu entres dès le premier tour. Tête de série n°{tete}.",
  "courrier.coupe.tirage.exempt": "Tirage au sort effectué : <b>{clubs} clubs engagés</b>, du Régional à l'Élite — un par association, comme le veut le règlement. Tu entres dès le premier tour, et tu en es exempté. Tête de série n°{tete}.",
  "courrier.coupe.fin.titre": "🏆 Coupe de France terminée",
  "courrier.coupe.fin.gagnee": "Ton équipe remporte la Coupe de France, face à {equipes} équipes engagées ! Prime : {prime}.",
  "courrier.coupe.fin.autre": "{nom} ({origine}) remporte la Coupe de France cette saison.",
  "courrier.effectif.grave.titre": "🚨 La direction s'inquiète de l'effectif",
  "courrier.effectif.leger.titre": "📉 La direction sur l'effectif",
  "courrier.effectif.grave.corps": "Un mot sur le groupe avant d'attaquer la saison. La moyenne de l'effectif est à <b>{force}</b>, quand la {division} tourne autour de <b>{milieu}</b> : <b>{ecart} points de retard</b>. À cet écart, l'entraînement seul ne rattrapera pas la saison — il fait gagner quelques points par an, pas dix. Le <b>marché des transferts</b> est le seul levier immédiat : quelques recrues bien choisies valent mieux qu'une saison de séances.",
  "courrier.effectif.leger.corps": "Un mot sur le groupe avant d'attaquer la saison. La moyenne de l'effectif est à <b>{force}</b>, quand la {division} tourne autour de <b>{milieu}</b> : <b>{ecart} points de retard</b>. L'entraînement peut combler ça sur une saison ou deux si le staff est bon. Un renfort ou deux sur le marché accélérerait les choses.",
  "courrier.stade.point.titre": "🏗️ La direction sur les installations",
  "courrier.stade.point.corps": "Un point avant d'entamer la saison. {detailHtml} Sportivement, rien ne nous empêche de viser plus haut — administrativement, si.",
  "courrier.stade.refus1.titre": "🚧 Une montée nous a déjà été refusée",
  "courrier.stade.refus1.corps": "La saison passée, nous avons gagné sur la piste et perdu au bureau : la montée nous a été <b>refusée</b> faute d'installation classée. {detailHtml}{chiffrageHtml} Recommencer une saison dans ces conditions, ce serait jouer pour rien.",
  "courrier.stade.refusN.titre": "🛑 {n} montées refusées — la salle est LA priorité",
  "courrier.stade.refusN.corps": "<b>{n} fois</b> nous avons mérité la montée sur le terrain, <b>{n} fois</b> elle nous a été refusée pour la même raison. {detailHtml}{chiffrageHtml} Tant que la salle n'est pas classée, tout l'argent mis dans l'effectif est de l'argent qui ne nous fera pas monter.",
  "courrier.stade.encore.titre": "🛑 La montée nous échappera encore",
  "courrier.stade.insiste.titre": "⚠️ La direction insiste sur les travaux",
  "courrier.stade.encore.corps": {"un": "Nous sommes {rang}{ordinal} et la montée se dessine. Or elle nous serait <b>refusée en l'état</b>. {detailHtml} C'est exactement ce qui nous est déjà arrivé {refus} fois. Il reste {n} journée pour agir.", "autres": "Nous sommes {rang}{ordinal} et la montée se dessine. Or elle nous serait <b>refusée en l'état</b>. {detailHtml} C'est exactement ce qui nous est déjà arrivé {refus} fois. Il reste {n} journées pour agir."},
  "courrier.stade.insiste.corps": "Nous sommes {rang}{ordinal} et la montée se dessine. Or elle nous serait <b>refusée en l'état</b>. {detailHtml}",
  "courrier.stade.homologue.titre": "✅ Installation homologuée",
  "courrier.stade.homologue.corps": "Les travaux sont réceptionnés. Notre salle est désormais de <b>classe {classe}</b> : elle satisfait aux exigences de la {division}. La montée ne dépend plus que du terrain.",
  "courrier.objectif.fixe.titre": "📋 Objectif de la direction",
  "courrier.objectif.fixe.corps": "Pour cette saison en {division}, la direction fixe l'objectif : {objectif}.",
  "courrier.objectif.atteint.titre": "✅ Objectif atteint",
  "courrier.objectif.manque.titre": "⚠️ Objectif manqué",
  "courrier.objectif.atteint.corps": "La direction est satisfaite : objectif « {objectif} » atteint ! Prime de confiance : {prime}.",
  "courrier.objectif.manque.corps": "La direction est déçue : objectif « {objectif} » non atteint (confiance de la direction en baisse : {confiance}/100).",
  "courrier.accession.decrochee.titre": "🎟️ Accession décrochée",
  "courrier.accession.phase.titre": "🎟️ Phase d'accession",
  "courrier.accession.pasDeTicket": {"un": "{rang}<sup>e</sup> de la poule : pas de ticket pour la phase d'accession. Notre ligue n'y envoie que <b>{n}</b> club, pris parmi les quatre premiers (art. 9.3 B). Il faut finir plus haut.", "autres": "{rang}<sup>e</sup> de la poule : pas de ticket pour la phase d'accession. Notre ligue n'y envoie que <b>{n}</b> clubs, pris parmi les quatre premiers (art. 9.3 B). Il faut finir plus haut."},
  "courrier.accession.gagnee": "Tournoi d'accession remporté : <b>{place}<sup>e</sup></b> sur les {places} places nationales. Direction la Nationale 3.",
  "courrier.accession.perdue": "Tournoi d'accession disputé, mais la place nous échappe : seules <b>{places} places</b> sont en jeu pour toute la France (art. 9.3 C). Gagner sa poule ne suffit pas — il faut sortir du tournoi.",
  "courrier.carriere.titre": "🎽 Fin de carrière nationale",
  "courrier.carriere.corps": "{portraitHtml}{nom} ({age} ans) quitte le championnat national.{statsHtml} Il compte bien continuer à patiner en régionale, plus tranquillement. Merci pour tout !",
  "courrier.espoir.titre": "🌟 Nouvel espoir",
  "courrier.espoir.corps": "{portraitHtml}{nom} ({age} ans, {poste}) sort du Pôle Espoir et signe son premier contrat professionnel avec le club.",
  "courrier.prolongation.titre": "Prolongation",
  "courrier.prolongation.corps": {"un": "{portraitHtml}{nom} a prolongé son contrat pour {n} saison.", "autres": "{portraitHtml}{nom} a prolongé son contrat pour {n} saisons."},
  "courrier.finContrat.titre": "Fin de contrat",
  "courrier.finContrat.corps": "{portraitHtml}{nom} a quitté le club, contrat arrivé à échéance (parti libre).",
  "courrier.retourPret.titre": "🔄 Retour de prêt",
  "courrier.retourPret.corps": "{nom} revient de prêt.",
  "courrier.pret.titre": "🔄 Prêt",
  "courrier.pret.corps": "{nom} est prêté pour le reste de la saison. Il reviendra à l'intersaison."
});

if (typeof PIECES_CHARGEES === 'object') PIECES_CHARGEES.textesfr = true;
