// textes-en.js — the game text in English
//
// Traduction. Ce qui n'est PAS traduit, et ne le sera pas : noms de joueurs, de clubs,
// de villes, de sponsors, prénoms de coachs. Ce sont des noms propres.
//
// Chargé par un <script> CLASSIQUE, pas un module ES : ceux-ci sont bloqués par CORS sous
// file://, et le jeu doit pouvoir s'ouvrir par double-clic.
//
// Une clé peut porter une chaîne, ou { un, autres } quand un pluriel est en jeu. Le
// français met 0 ET 1 au singulier, l'anglais met 0 au pluriel : c'est `REGLE_PLURIEL` qui
// tranche, pas ce fichier.
//
// Les marqueurs {nom} sont substitués par `T(cle, params)`. L'échappement reste à
// l'appelant : `T('cle', { nom: escHtml(p.nom) })`.

// Pas de garde `typeof` autour de cette affectation : `TEXTES` est déclaré dans le bloc
// d'amorçage de la page, donc toujours là. Un garde ferait échouer le chargement EN SILENCE
// si l'ordre changeait un jour — et c'est exactement le défaut qu'on a payé une fois.
Object.assign(TEXTES.en, {
  "ecran.effectif.label": "Squad",
  "ecran.effectif.court": "Squad",
  "ecran.club.label": "Club",
  "ecran.club.court": "Club",
  "ecran.entrainement.label": "Training",
  "ecran.entrainement.court": "Train.",
  "ecran.classement.label": "Standings",
  "ecran.classement.court": "Table",
  "ecran.calendrier.label": "Fixtures",
  "ecran.calendrier.court": "Fixtures",
  "ecran.transferts.label": "Transfers",
  "ecran.transferts.court": "Transf.",
  "ecran.inbox.label": "Messages",
  "ecran.inbox.court": "Messages",
  "ecran.historique.label": "History",
  "ecran.historique.court": "History",
  "ecran.coupe.label": "Cup",
  "ecran.coupe.court": "Cup",
  "ecran.aide.label": "Help",
  "ecran.aide.court": "Help",
  "ecran.options.label": "Settings",
  "ecran.options.court": "Settings",
  "reglages.langue.titre": "Language",
  "reglages.langue.note": "The whole game follows this choice. Player, club and town names stay as they are — they are proper nouns.",
  "reglages.son.titre": "Sound",
  "reglages.son.note": "The music changes with the screen. It stops on its own when you leave the app.",
  "reglages.son.active": "On",
  "reglages.son.coupee": "Muted",
  "reglages.son.volume": "Volume",
  "reglages.partie.titre": "Current game",
  "reglages.partie.note": "Go back to the title screen to switch slot or start another game. Yours is saved automatically — you will find it exactly as you left it.",
  "reglages.partie.retour": "Back to title screen",
  "reglages.partie.confirmer": "Back to title",
  "reglages.partie.question": "Go back to the title screen?\\n\\nYour game is saved — you will find it in this slot.",
  "reglages.barre.titre": "Bottom bar",
  "reglages.barre.note": "Choose which screens appear directly, and in what order. The rest stay available under the « More » button.",
  "reglages.barre.retirer": "Remove {ecran} from the bar",
  "reglages.barre.ajouter": "Add {ecran} to the bar",
  "reglages.barre.capacite": {"un": "This screen shows <b>{n} entry</b> at its current width ({largeur} px).", "autres": "This screen shows <b>{n} entries</b> at its current width ({largeur} px)."},
  "reglages.barre.reste": {"un": "The last screen is under « More ».", "autres": "The other {n} screens are under « More »."},
  "reglages.barre.tout": "Everything fits in the bar, the « More » button disappears.",
  "reglages.barre.elargis": "Widen the window and the bar fills out by itself.",
  "reglages.version": "version {n}",

  // ---- tranche 2 : bandeau, bouton d'action, tiroir
  "bandeau.saison": "season",
  "bandeau.journee": "matchday",
  "bandeau.budget": "Budget",
  "bandeau.objectif": "Target",
  "bandeau.direction": "Board",
  "bandeau.rang": "{rang} of {total}",
  "nav.plus": "More",
  "action.journee": "Play matchday {n}",
  "action.coupe.tirage": "Draw the Coupe de France",
  "action.coupe.resultats": "Coupe de France results",
  "action.coupe.jouer": "Play the Coupe de France tie",
  "action.playoffs.lancer": "Start the playoffs (Top 8)",
  "action.playoffs.final": "See the final playoff result",
  "action.playoffs.quart": "Play a quarter-final",
  "action.playoffs.demi": "Play a semi-final",
  "action.playoffs.finale": "Play a final",
  "action.bilan": "End-of-season review",

  // ---- courrier
  "courrier.date": "Season {saison} · matchday {journee}",
  "courrier.ta-reponse": "Your answer: {dit}",
  "courrier.brut.titre": "{titreHtml}",
  "courrier.brut.corps": "{corpsHtml}",
  "courrier.brouille.deplace": "Your answer: {dit} {nom} moves to line {ligne}.",
  "courrier.brouille.impossible": "No line can take him. He stays where he is.",
  "courrier.vestiaire.partir.titre": "🚪 {nom} wants out",
  "courrier.vestiaire.tete.titre": "😠 {nom} is sulking",
  "courrier.vestiaire.partir.corps": {"un": "{portraitHtml}{nom} came to see me. He has had enough of this situation and asks to leave the club. {n} game played this season.", "autres": "{portraitHtml}{nom} came to see me. He has had enough of this situation and asks to leave the club. {n} games played this season."},
  "courrier.vestiaire.tete.corps": {"un": "{portraitHtml}{nom} is still fuming. {n} game played this season, and he reckons he is worth more than that.", "autres": "{portraitHtml}{nom} is still fuming. {n} games played this season, and he reckons he is worth more than that."},
  "courrier.engagement.tenu.titre": "🤝 Promise kept — {nom}",
  "courrier.engagement.rompu.titre": "💥 Promise broken — {nom}",
  "courrier.engagement.chiffre.tenu": "{nom} played {presences} of the last {journees} matchdays, as promised. He will not forget it.",
  "courrier.engagement.chiffre.rompu": "{nom} only played {presences} times out of {journees}. He had my word. He is asking to leave.",
  "courrier.engagement.parole.tenue": "{nom} is back at work. The talk got through.",
  "courrier.engagement.parole.rompue": "{nom} saw none of what I promised him. He will never believe me again.",
  "courrier.objectifJoueur.atteint.titre": "🎯 Personal target met",
  "courrier.objectifJoueur.manque.titre": "📉 Personal target missed",
  "courrier.objectifJoueur.atteint.corps": "{nom} met his target of {cible} goals ({buts} scored) — morale up.",
  "courrier.objectifJoueur.manque.corps": "{nom} only scored {buts} against a target of {cible} — a little disappointed.",
  "courrier.coupe.titre": "🏆 Coupe de France",
  "courrier.coupe.auto": "The cup was settled automatically before the playoffs began (winner: {vainqueur}).",
  "courrier.coupe.tirage.tard": "The draw is done: <b>{clubs} clubs entered</b>, from Régional to Élite — one per association, as the rules require. Your level means you enter later, when only {entree} teams are left. Seeded no. {tete}.",
  "courrier.coupe.tirage.premier": "The draw is done: <b>{clubs} clubs entered</b>, from Régional to Élite — one per association, as the rules require. You enter in the first round. Seeded no. {tete}.",
  "courrier.coupe.tirage.exempt": "The draw is done: <b>{clubs} clubs entered</b>, from Régional to Élite — one per association, as the rules require. You enter in the first round, and you have a bye. Seeded no. {tete}.",
  "courrier.coupe.fin.titre": "🏆 Coupe de France over",
  "courrier.coupe.fin.gagnee": "Your team wins the Coupe de France, against {equipes} teams entered! Prize: {prime}.",
  "courrier.coupe.fin.autre": "{nom} ({origine}) wins the Coupe de France this season.",
  "courrier.effectif.grave.titre": "🚨 The board is worried about the squad",
  "courrier.effectif.leger.titre": "📉 The board on the squad",
  "courrier.effectif.grave.corps": "A word on the group before the season starts. The squad averages <b>{force}</b>, while {division} sits around <b>{milieu}</b>: <b>{ecart} points behind</b>. At that gap, training alone will not save the season — it gains a few points a year, not ten. The <b>transfer market</b> is the only immediate lever: a few well-chosen signings beat a season of sessions.",
  "courrier.effectif.leger.corps": "A word on the group before the season starts. The squad averages <b>{force}</b>, while {division} sits around <b>{milieu}</b>: <b>{ecart} points behind</b>. Training can close that in a season or two with good staff. One or two signings would speed it up.",
  "courrier.stade.point.titre": "🏗️ The board on the facilities",
  "courrier.stade.point.corps": "A word before the season starts. {detailHtml} On the court, nothing stops us aiming higher — on paper, plenty does.",
  "courrier.stade.refus1.titre": "🚧 We have already been denied a promotion",
  "courrier.stade.refus1.corps": "Last season we won on the court and lost at the desk: promotion was <b>denied</b> for want of a rated venue. {detailHtml}{chiffrageHtml} Starting another season on these terms would mean playing for nothing.",
  "courrier.stade.refusN.titre": "🛑 {n} promotions denied — the venue is THE priority",
  "courrier.stade.refusN.corps": "<b>{n} times</b> we earned promotion on the court, <b>{n} times</b> it was denied for the same reason. {detailHtml}{chiffrageHtml} Until the venue is rated, every euro spent on the squad is money that will not get us up.",
  "courrier.stade.encore.titre": "🛑 Promotion will slip away again",
  "courrier.stade.insiste.titre": "⚠️ The board insists on the building work",
  "courrier.stade.encore.corps": {"un": "We are {rang}{ordinal} and promotion is taking shape. It would be <b>denied as things stand</b>. {detailHtml} That is exactly what has already happened to us {refus} times. {n} matchday left to act.", "autres": "We are {rang}{ordinal} and promotion is taking shape. It would be <b>denied as things stand</b>. {detailHtml} That is exactly what has already happened to us {refus} times. {n} matchdays left to act."},
  "courrier.stade.insiste.corps": "We are {rang}{ordinal} and promotion is taking shape. It would be <b>denied as things stand</b>. {detailHtml}",
  "courrier.stade.homologue.titre": "✅ Venue approved",
  "courrier.stade.homologue.corps": "The work has been signed off. Our venue is now <b>class {classe}</b>: it meets the requirements for {division}. Promotion now depends on results alone.",
  "courrier.objectif.fixe.titre": "📋 The board sets its target",
  "courrier.objectif.fixe.corps": "For this season in {division}, the board sets the target: {objectif}.",
  "courrier.objectif.atteint.titre": "✅ Target met",
  "courrier.objectif.manque.titre": "⚠️ Target missed",
  "courrier.objectif.atteint.corps": "The board is satisfied: target « {objectif} » met! Confidence bonus: {prime}.",
  "courrier.objectif.manque.corps": "The board is disappointed: target « {objectif} » not met (board confidence down: {confiance}/100).",
  "courrier.accession.decrochee.titre": "🎟️ Promotion play-off won",
  "courrier.accession.phase.titre": "🎟️ Promotion play-off",
  "courrier.accession.pasDeTicket": {"un": "{rang}<sup>th</sup> in the group: no ticket for the promotion play-off. Our league sends only <b>{n}</b> club, taken from the top four (art. 9.3 B). We must finish higher.", "autres": "{rang}<sup>th</sup> in the group: no ticket for the promotion play-off. Our league sends only <b>{n}</b> clubs, taken from the top four (art. 9.3 B). We must finish higher."},
  "courrier.accession.gagnee": "Promotion tournament won: <b>{place}<sup>th</sup></b> of the {places} national places. Nationale 3 next.",
  "courrier.accession.perdue": "We played the promotion tournament, but the place slips away: only <b>{places} places</b> are up for grabs in the whole country (art. 9.3 C). Winning your group is not enough — you must come through the tournament.",
  "courrier.carriere.titre": "🎽 End of a national career",
  "courrier.carriere.corps": "{portraitHtml}{nom} ({age}) is leaving the national league.{statsHtml} He fully intends to keep skating at regional level, more quietly. Thanks for everything!",
  "courrier.espoir.titre": "🌟 New prospect",
  "courrier.espoir.corps": "{portraitHtml}{nom} ({age}, {poste}) comes out of the academy and signs his first professional contract with the club.",
  "courrier.prolongation.titre": "Contract extended",
  "courrier.prolongation.corps": {"un": "{portraitHtml}{nom} has extended his contract by {n} season.", "autres": "{portraitHtml}{nom} has extended his contract by {n} seasons."},
  "courrier.finContrat.titre": "Contract over",
  "courrier.finContrat.corps": "{portraitHtml}{nom} has left the club, his contract having run out (free agent).",
  "courrier.retourPret.titre": "🔄 Back from loan",
  "courrier.retourPret.corps": "{nom} is back from his loan.",
  "courrier.pret.titre": "🔄 Loan",
  "courrier.pret.corps": "{nom} is loaned out for the rest of the season. He will be back in the off-season.",

  // ---- presse, vestiaire, événements
  "presse.accroche.elogieux.0": "📰 A statement",
  "presse.accroche.elogieux.1": "📰 Style and substance",
  "presse.accroche.elogieux.2": "📰 A masterclass",
  "presse.accroche.elogieux.3": "📰 Steamrollered",
  "presse.accroche.neutre.0": "📰 A win that counts",
  "presse.accroche.neutre.1": "📰 Job done",
  "presse.accroche.neutre.2": "📰 Within themselves",
  "presse.accroche.severe.0": "📰 A night to forget",
  "presse.accroche.severe.1": "📰 The fall",
  "presse.accroche.severe.2": "📰 Nothing worked",
  "presse.accroche.severe.3": "📰 A rude awakening awaits",
  "presse.corps.exploit": "<i>{journal}</i> — {nous} {mien}–{sien} {eux}. Nobody saw that result coming against the league leaders.",
  "presse.corps.contreperf": "<i>{journal}</i> — {nous} {mien}–{sien} {eux}. A defeat to the bottom club, hard to explain away.",
  "presse.corps.large": "<i>{journal}</i> — {nous} {mien}–{sien} {eux}. The margin says everything about the control on show.",
  "presse.corps.lourde": "<i>{journal}</i> — {nous} {mien}–{sien} {eux}. The scoreline is harsh, but it is not stolen.",
  "presse.corps.simple": "<i>{journal}</i> — {nous} {mien}–{sien} {eux}.",
  "presse.corps.exploit.triple": "<i>{journal}</i> — {nous} {mien}–{sien} {eux}. Nobody saw that result coming against the league leaders. <b>{triple}</b> helps himself to a hat-trick.",
  "presse.corps.contreperf.triple": "<i>{journal}</i> — {nous} {mien}–{sien} {eux}. A defeat to the bottom club, hard to explain away. <b>{triple}</b> still helps himself to a hat-trick.",
  "presse.corps.large.triple": "<i>{journal}</i> — {nous} {mien}–{sien} {eux}. The margin says everything about the control on show. <b>{triple}</b> helps himself to a hat-trick.",
  "presse.corps.lourde.triple": "<i>{journal}</i> — {nous} {mien}–{sien} {eux}. The scoreline is harsh, but it is not stolen. <b>{triple}</b> still helps himself to a hat-trick.",
  "presse.corps.simple.triple": "<i>{journal}</i> — {nous} {mien}–{sien} {eux}. <b>{triple}</b> helps himself to a hat-trick.",
  "reponse.presse.mesure.label": "Stay measured",
  "reponse.presse.mesure.dit": "“One win, nothing more. We are back at work tomorrow.”",
  "reponse.presse.feliciter.label": "Praise the group",
  "reponse.presse.feliciter.dit": "“They were immense. Tonight belongs to them.”",
  "reponse.presse.concentre.label": "Stay focused",
  "reponse.presse.concentre.dit": "“We take the points and move on. Nothing is settled.”",
  "reponse.presse.caractere.label": "Praise their character",
  "reponse.presse.caractere.dit": "“They did not panic. That is what I take from it.”",
  "reponse.presse.defendre.label": "Defend my players",
  "reponse.presse.defendre.dit": "“Nobody hid out there. The group is not the problem.”",
  "reponse.presse.assumer.label": "Take the blame publicly",
  "reponse.presse.assumer.dit": "“That was unworthy of this club. Starting with me.”",
  "reponse.vestiaire.rassurer.label": "Reassure him",
  "reponse.vestiaire.rassurer.dit": "“You matter to this group. Keep a cool head.”",
  "reponse.vestiaire.promettre.label": "Promise him game time",
  "reponse.vestiaire.promettre.dit": "“You will play. I am telling you to your face, not into thin air.”",
  "reponse.vestiaire.ignorer.label": "Say nothing",
  "reponse.vestiaire.ignorer.dit": "“…”",
  "reponse.brouille.separer.label": "Split their lines",
  "reponse.brouille.separer.dit": "“They will not play together again.”",
  "reponse.brouille.laisser.label": "Let them sort it out",
  "reponse.brouille.laisser.dit": "“They are adults. Let them talk.”",
  "evenement.accrochage.titre": "🔥 Row in the changing room",
  "evenement.accrochage.corps": "{a} and {b} had words after the game. They play on the same line, and it shows now.",
  "evenement.parrainage.titre": "🧭 {ancien} takes {jeune} under his wing",
  "evenement.parrainage.corps": "The veteran spent the week working with the youngster. It will show on the court, and it already shows in the changing room.",
  "evenement.jalousie.titre": "😤 {frustre} is struggling with the competition",
  "evenement.jalousie.corps": "He reckons he is worth more than {rival}, who plays in his place. The mood between them is suffering.",
  "evenement.soiree.titre": "🎉 Club night",
  "evenement.soiree.corps": "Everyone was there — players, volunteers and committee. Nights like these are what hold a group together over a season."
});

if (typeof PIECES_CHARGEES === 'object') PIECES_CHARGEES.textesen = true;
