// textes-fr.js — les textes du jeu en français
//
// Langue d'origine du jeu, et langue de repli de toutes les autres : quand une clé
// manque ailleurs, `T()` revient ici plutôt que de laisser un trou blanc.
//
// Chargé par un <script> CLASSIQUE, pas un module ES : ceux-ci sont bloqués par CORS sous
// file://, et le jeu doit pouvoir s'ouvrir par double-clic.
//
// Une clé peut porter une chaîne, ou { un, autres } quand un pluriel est en jeu. Le
// français met 0 ET 1 au singulier, l'anglais met 0 au pluriel : c'est `REGLE_PLURIEL` qui
// tranche, pas ce fichier.
//
// Les marqueurs {nom} sont substitués par `T(cle, params)`. L'échappement reste à
// l'appelant : `T('cle', { nom: escHtml(p.nom) })`.

// Pas de garde `typeof` autour de cette affectation : `TEXTES` est déclaré dans le bloc
// d'amorçage de la page, donc toujours là. Un garde ferait échouer le chargement EN SILENCE
// si l'ordre changeait un jour — et c'est exactement le défaut qu'on a payé une fois.
Object.assign(TEXTES.fr, {
  "ecran.effectif.label": "Effectif",
  "ecran.effectif.court": "Effectif",
  "ecran.club.label": "Club",
  "ecran.club.court": "Club",
  "ecran.entrainement.label": "Entraînement",
  "ecran.entrainement.court": "Entraîn.",
  "ecran.classement.label": "Classement",
  "ecran.classement.court": "Classem.",
  "ecran.calendrier.label": "Calendrier",
  "ecran.calendrier.court": "Calend.",
  "ecran.transferts.label": "Transferts",
  "ecran.transferts.court": "Transf.",
  "ecran.inbox.label": "Messages",
  "ecran.inbox.court": "Messages",
  "ecran.historique.label": "Historique",
  "ecran.historique.court": "Histor.",
  "ecran.coupe.label": "Coupe",
  "ecran.coupe.court": "Coupe",
  "ecran.aide.label": "Aide",
  "ecran.aide.court": "Aide",
  "ecran.options.label": "Réglages",
  "ecran.options.court": "Réglages",
  "reglages.langue.titre": "Langue",
  "reglages.langue.note": "Le jeu tout entier suit ce choix. Les noms de joueurs, de clubs et de villes ne changent pas — ce sont des noms propres.",
  "reglages.son.titre": "Son",
  "reglages.son.note": "La musique change selon l'écran. Elle se coupe toute seule quand tu quittes l'application.",
  "reglages.son.active": "Activée",
  "reglages.son.coupee": "Coupée",
  "reglages.son.volume": "Volume",
  "reglages.partie.titre": "Partie en cours",
  "reglages.partie.note": "Reviens à l'écran titre pour changer d'emplacement ou démarrer une autre partie. La tienne est sauvegardée automatiquement, tu la retrouveras telle quelle.",
  "reglages.partie.retour": "Retour à l'écran titre",
  "reglages.partie.confirmer": "Revenir au titre",
  "reglages.partie.question": "Revenir à l'écran titre ?\\n\\nTa partie est sauvegardée, tu la retrouveras à cet emplacement.",
  "reglages.barre.titre": "Barre du bas",
  "reglages.barre.note": "Choisis les écrans qui apparaissent directement, et leur ordre. Les autres restent accessibles par le bouton « Plus ».",
  "reglages.barre.retirer": "Retirer {ecran} de la barre",
  "reglages.barre.ajouter": "Ajouter {ecran} à la barre",
  "reglages.barre.capacite": {"un": "Cet écran affiche <b>{n} entrée</b> à sa largeur actuelle ({largeur} px).", "autres": "Cet écran affiche <b>{n} entrées</b> à sa largeur actuelle ({largeur} px)."},
  "reglages.barre.reste": {"un": "Le dernier écran est dans « Plus ».", "autres": "Les {n} écrans restants sont dans « Plus »."},
  "reglages.barre.tout": "Tout tient dans la barre, le bouton « Plus » disparaît.",
  "reglages.barre.elargis": "Élargis la fenêtre et la barre s'étoffe d'elle-même.",
  "reglages.version": "version {n}",

  // ---- tranche 2 : bandeau, bouton d'action, tiroir
  "bandeau.saison": "saison",
  "bandeau.journee": "journée",
  "bandeau.budget": "Budget",
  "bandeau.objectif": "Objectif",
  "bandeau.direction": "Direction",
  "bandeau.rang": "{rang}e/{total}",
  "nav.plus": "Plus",
  "action.journee": "Jouer la journée {n}",
  "action.coupe.tirage": "Lancer le tirage de la Coupe de France",
  "action.coupe.resultats": "Résultats de la Coupe de France",
  "action.coupe.jouer": "Jouer le match de Coupe de France",
  "action.playoffs.lancer": "Lancer les playoffs (Top 8)",
  "action.playoffs.final": "Voir le résultat final des playoffs",
  "action.playoffs.quart": "Jouer un match de quart de finale",
  "action.playoffs.demi": "Jouer un match de demi-finale",
  "action.playoffs.finale": "Jouer un match de la finale",
  "action.bilan": "Bilan de fin de saison",

  // ---- courrier
  "courrier.date": "Saison {saison} · journée {journee}",
  "courrier.ta-reponse": "Ta réponse : {dit}",
  "courrier.brut.titre": "{titreHtml}",
  "courrier.brut.corps": "{corpsHtml}",
  "courrier.brouille.deplace": "Ta réponse : {dit} {nom} passe en ligne {ligne}.",
  "courrier.brouille.impossible": "Aucune ligne ne peut l'accueillir. Il reste où il est.",
  "courrier.vestiaire.partir.titre": "🚪 {nom} veut partir",
  "courrier.vestiaire.tete.titre": "😠 {nom} fait la tête",
  "courrier.vestiaire.partir.corps": {"un": "{portraitHtml}{nom} est venu me voir. Il ne veut plus de cette situation et demande à quitter le club. {n} match joué cette saison.", "autres": "{portraitHtml}{nom} est venu me voir. Il ne veut plus de cette situation et demande à quitter le club. {n} matchs joués cette saison."},
  "courrier.vestiaire.tete.corps": {"un": "{portraitHtml}{nom} ne décolère pas. {n} match joué cette saison, et il estime valoir mieux que ça.", "autres": "{portraitHtml}{nom} ne décolère pas. {n} matchs joués cette saison, et il estime valoir mieux que ça."},
  "courrier.engagement.tenu.titre": "🤝 Parole tenue — {nom}",
  "courrier.engagement.rompu.titre": "💥 Parole non tenue — {nom}",
  "courrier.engagement.chiffre.tenu": "{nom} a joué {presences} des {journees} dernières journées, comme promis. Il ne l'oubliera pas.",
  "courrier.engagement.chiffre.rompu": "{nom} n'a joué que {presences} fois sur {journees}. Il avait ma parole. Il demande à partir.",
  "courrier.engagement.parole.tenue": "{nom} s'est remis au travail. Le discours a porté.",
  "courrier.engagement.parole.rompue": "{nom} n'a rien vu venir de ce que je lui avais dit. Il ne me croira plus.",
  "courrier.objectifJoueur.atteint.titre": "🎯 Objectif individuel atteint",
  "courrier.objectifJoueur.manque.titre": "📉 Objectif individuel manqué",
  "courrier.objectifJoueur.atteint.corps": "{nom} a atteint son objectif de {cible} buts ({buts} inscrits) — moral en hausse.",
  "courrier.objectifJoueur.manque.corps": "{nom} n'a marqué que {buts} but(s) sur un objectif de {cible} — un peu déçu.",
  "courrier.coupe.titre": "🏆 Coupe de France",
  "courrier.coupe.auto": "La coupe a été résolue automatiquement avant le coup d'envoi des playoffs (vainqueur : {vainqueur}).",
  "courrier.coupe.tirage.tard": "Tirage au sort effectué : <b>{clubs} clubs engagés</b>, du Régional à l'Élite — un par association, comme le veut le règlement. Ton niveau te fait entrer plus tard, quand il ne restera que {entree} équipes. Tête de série n°{tete}.",
  "courrier.coupe.tirage.premier": "Tirage au sort effectué : <b>{clubs} clubs engagés</b>, du Régional à l'Élite — un par association, comme le veut le règlement. Tu entres dès le premier tour. Tête de série n°{tete}.",
  "courrier.coupe.tirage.exempt": "Tirage au sort effectué : <b>{clubs} clubs engagés</b>, du Régional à l'Élite — un par association, comme le veut le règlement. Tu entres dès le premier tour, et tu en es exempté. Tête de série n°{tete}.",
  "courrier.coupe.fin.titre": "🏆 Coupe de France terminée",
  "courrier.coupe.fin.gagnee": "Ton équipe remporte la Coupe de France, face à {equipes} équipes engagées ! Prime : {prime}.",
  "courrier.coupe.fin.autre": "{nom} ({origine}) remporte la Coupe de France cette saison.",
  "courrier.effectif.grave.titre": "🚨 La direction s'inquiète de l'effectif",
  "courrier.effectif.leger.titre": "📉 La direction sur l'effectif",
  "courrier.effectif.grave.corps": "Un mot sur le groupe avant d'attaquer la saison. La moyenne de l'effectif est à <b>{force}</b>, quand la {division} tourne autour de <b>{milieu}</b> : <b>{ecart} points de retard</b>. À cet écart, l'entraînement seul ne rattrapera pas la saison — il fait gagner quelques points par an, pas dix. Le <b>marché des transferts</b> est le seul levier immédiat : quelques recrues bien choisies valent mieux qu'une saison de séances.",
  "courrier.effectif.leger.corps": "Un mot sur le groupe avant d'attaquer la saison. La moyenne de l'effectif est à <b>{force}</b>, quand la {division} tourne autour de <b>{milieu}</b> : <b>{ecart} points de retard</b>. L'entraînement peut combler ça sur une saison ou deux si le staff est bon. Un renfort ou deux sur le marché accélérerait les choses.",
  "courrier.stade.point.titre": "🏗️ La direction sur les installations",
  "courrier.stade.point.corps": "Un point avant d'entamer la saison. {detailHtml} Sportivement, rien ne nous empêche de viser plus haut — administrativement, si.",
  "courrier.stade.refus1.titre": "🚧 Une montée nous a déjà été refusée",
  "courrier.stade.refus1.corps": "La saison passée, nous avons gagné sur la piste et perdu au bureau : la montée nous a été <b>refusée</b> faute d'installation classée. {detailHtml}{chiffrageHtml} Recommencer une saison dans ces conditions, ce serait jouer pour rien.",
  "courrier.stade.refusN.titre": "🛑 {n} montées refusées — la salle est LA priorité",
  "courrier.stade.refusN.corps": "<b>{n} fois</b> nous avons mérité la montée sur le terrain, <b>{n} fois</b> elle nous a été refusée pour la même raison. {detailHtml}{chiffrageHtml} Tant que la salle n'est pas classée, tout l'argent mis dans l'effectif est de l'argent qui ne nous fera pas monter.",
  "courrier.stade.encore.titre": "🛑 La montée nous échappera encore",
  "courrier.stade.insiste.titre": "⚠️ La direction insiste sur les travaux",
  "courrier.stade.encore.corps": {"un": "Nous sommes {rang}{ordinal} et la montée se dessine. Or elle nous serait <b>refusée en l'état</b>. {detailHtml} C'est exactement ce qui nous est déjà arrivé {refus} fois. Il reste {n} journée pour agir.", "autres": "Nous sommes {rang}{ordinal} et la montée se dessine. Or elle nous serait <b>refusée en l'état</b>. {detailHtml} C'est exactement ce qui nous est déjà arrivé {refus} fois. Il reste {n} journées pour agir."},
  "courrier.stade.insiste.corps": "Nous sommes {rang}{ordinal} et la montée se dessine. Or elle nous serait <b>refusée en l'état</b>. {detailHtml}",
  "courrier.stade.homologue.titre": "✅ Installation homologuée",
  "courrier.stade.homologue.corps": "Les travaux sont réceptionnés. Notre salle est désormais de <b>classe {classe}</b> : elle satisfait aux exigences de la {division}. La montée ne dépend plus que du terrain.",
  "courrier.objectif.fixe.titre": "📋 Objectif de la direction",
  "courrier.objectif.fixe.corps": "Pour cette saison en {division}, la direction fixe l'objectif : {objectif}.",
  "courrier.objectif.atteint.titre": "✅ Objectif atteint",
  "courrier.objectif.manque.titre": "⚠️ Objectif manqué",
  "courrier.objectif.atteint.corps": "La direction est satisfaite : objectif « {objectif} » atteint ! Prime de confiance : {prime}.",
  "courrier.objectif.manque.corps": "La direction est déçue : objectif « {objectif} » non atteint (confiance de la direction en baisse : {confiance}/100).",
  "courrier.accession.decrochee.titre": "🎟️ Accession décrochée",
  "courrier.accession.phase.titre": "🎟️ Phase d'accession",
  "courrier.accession.pasDeTicket": {"un": "{rang}<sup>e</sup> de la poule : pas de ticket pour la phase d'accession. Notre ligue n'y envoie que <b>{n}</b> club, pris parmi les quatre premiers (art. 9.3 B). Il faut finir plus haut.", "autres": "{rang}<sup>e</sup> de la poule : pas de ticket pour la phase d'accession. Notre ligue n'y envoie que <b>{n}</b> clubs, pris parmi les quatre premiers (art. 9.3 B). Il faut finir plus haut."},
  "courrier.accession.gagnee": "Tournoi d'accession remporté : <b>{place}<sup>e</sup></b> sur les {places} places nationales. Direction la Nationale 3.",
  "courrier.accession.perdue": "Tournoi d'accession disputé, mais la place nous échappe : seules <b>{places} places</b> sont en jeu pour toute la France (art. 9.3 C). Gagner sa poule ne suffit pas — il faut sortir du tournoi.",
  "courrier.carriere.titre": "🎽 Fin de carrière nationale",
  "courrier.carriere.corps": "{portraitHtml}{nom} ({age} ans) quitte le championnat national.{statsHtml} Il compte bien continuer à patiner en régionale, plus tranquillement. Merci pour tout !",
  "courrier.espoir.titre": "🌟 Nouvel espoir",
  "courrier.espoir.corps": "{portraitHtml}{nom} ({age} ans, {poste}) sort du Pôle Espoir et signe son premier contrat professionnel avec le club.",
  "courrier.prolongation.titre": "Prolongation",
  "courrier.prolongation.corps": {"un": "{portraitHtml}{nom} a prolongé son contrat pour {n} saison.", "autres": "{portraitHtml}{nom} a prolongé son contrat pour {n} saisons."},
  "courrier.finContrat.titre": "Fin de contrat",
  "courrier.finContrat.corps": "{portraitHtml}{nom} a quitté le club, contrat arrivé à échéance (parti libre).",
  "courrier.retourPret.titre": "🔄 Retour de prêt",
  "courrier.retourPret.corps": "{nom} revient de prêt.",
  "courrier.pret.titre": "🔄 Prêt",
  "courrier.pret.corps": "{nom} est prêté pour le reste de la saison. Il reviendra à l'intersaison.",

  // ---- presse, vestiaire, événements
  "presse.accroche.elogieux.0": "📰 Démonstration",
  "presse.accroche.elogieux.1": "📰 La manière et le résultat",
  "presse.accroche.elogieux.2": "📰 Un récital",
  "presse.accroche.elogieux.3": "📰 Le rouleau compresseur",
  "presse.accroche.neutre.0": "📰 Une victoire qui compte",
  "presse.accroche.neutre.1": "📰 L'essentiel est assuré",
  "presse.accroche.neutre.2": "📰 Sans forcer",
  "presse.accroche.severe.0": "📰 Soirée à oublier",
  "presse.accroche.severe.1": "📰 La chute",
  "presse.accroche.severe.2": "📰 Rien n'a fonctionné",
  "presse.accroche.severe.3": "📰 Le réveil sera difficile",
  "presse.corps.exploit": "<i>{journal}</i> — {nous} {mien}–{sien} {eux}. Personne n'attendait ce résultat face au leader.",
  "presse.corps.contreperf": "<i>{journal}</i> — {nous} {mien}–{sien} {eux}. Une défaite contre la lanterne rouge, difficile à expliquer.",
  "presse.corps.large": "<i>{journal}</i> — {nous} {mien}–{sien} {eux}. L'écart dit tout de la maîtrise affichée.",
  "presse.corps.lourde": "<i>{journal}</i> — {nous} {mien}–{sien} {eux}. Le score est sévère, mais il n'est pas volé.",
  "presse.corps.simple": "<i>{journal}</i> — {nous} {mien}–{sien} {eux}.",
  "presse.corps.exploit.triple": "<i>{journal}</i> — {nous} {mien}–{sien} {eux}. Personne n'attendait ce résultat face au leader. <b>{triple}</b> s'offre un triplé.",
  "presse.corps.contreperf.triple": "<i>{journal}</i> — {nous} {mien}–{sien} {eux}. Une défaite contre la lanterne rouge, difficile à expliquer. <b>{triple}</b> s'offre tout de même un triplé.",
  "presse.corps.large.triple": "<i>{journal}</i> — {nous} {mien}–{sien} {eux}. L'écart dit tout de la maîtrise affichée. <b>{triple}</b> s'offre un triplé.",
  "presse.corps.lourde.triple": "<i>{journal}</i> — {nous} {mien}–{sien} {eux}. Le score est sévère, mais il n'est pas volé. <b>{triple}</b> s'offre tout de même un triplé.",
  "presse.corps.simple.triple": "<i>{journal}</i> — {nous} {mien}–{sien} {eux}. <b>{triple}</b> s'offre un triplé.",
  "reponse.presse.mesure.label": "Rester mesuré",
  "reponse.presse.mesure.dit": "« Une victoire, rien de plus. On se remet au travail dès demain. »",
  "reponse.presse.feliciter.label": "Féliciter le groupe",
  "reponse.presse.feliciter.dit": "« Ils ont été énormes. Ce soir, c'est pour eux. »",
  "reponse.presse.concentre.label": "Rester concentré",
  "reponse.presse.concentre.dit": "« On prend les points et on avance. Rien n'est fait. »",
  "reponse.presse.caractere.label": "Saluer le caractère",
  "reponse.presse.caractere.dit": "« Ils ne se sont pas affolés. C'est ce que je retiens. »",
  "reponse.presse.defendre.label": "Défendre mes joueurs",
  "reponse.presse.defendre.dit": "« Personne ne s'est caché. Le groupe n'est pas en cause. »",
  "reponse.presse.assumer.label": "Assumer publiquement",
  "reponse.presse.assumer.dit": "« C'est indigne de ce club. À commencer par moi. »",
  "reponse.vestiaire.rassurer.label": "Le rassurer",
  "reponse.vestiaire.rassurer.dit": "« Tu comptes pour ce groupe. Garde la tête froide. »",
  "reponse.vestiaire.promettre.label": "Promettre du temps de jeu",
  "reponse.vestiaire.promettre.dit": "« Tu vas jouer. Je te le dis en face, pas dans le vide. »",
  "reponse.vestiaire.ignorer.label": "Ne rien répondre",
  "reponse.vestiaire.ignorer.dit": "« … »",
  "reponse.brouille.separer.label": "Les séparer de ligne",
  "reponse.brouille.separer.dit": "« Ils ne joueront plus ensemble. »",
  "reponse.brouille.laisser.label": "Les laisser régler ça",
  "reponse.brouille.laisser.dit": "« Ce sont des adultes. Qu'ils se parlent. »",
  "evenement.accrochage.titre": "🔥 Accrochage au vestiaire",
  "evenement.accrochage.corps": "{a} et {b} en sont venus aux mots après la rencontre. Ils jouent sur la même ligne, et ça se voit désormais.",
  "evenement.parrainage.titre": "🧭 {ancien} prend {jeune} sous son aile",
  "evenement.parrainage.corps": "L'ancien a passé la semaine à travailler avec le jeune. Ça se verra sur la piste, et ça se voit déjà au vestiaire.",
  "evenement.jalousie.titre": "😤 {frustre} supporte mal la concurrence",
  "evenement.jalousie.corps": "Il estime valoir mieux que {rival}, qui joue à sa place. L'ambiance entre eux s'en ressent.",
  "evenement.soiree.titre": "🎉 Soirée du club",
  "evenement.soiree.corps": "Tout le monde était là, joueurs, bénévoles et dirigeants. Ce sont ces soirées-là qui font tenir un groupe sur une saison.",

  // ---- écran Effectif, cartes et tableau
  "stat.general": "Général",
  "stat.tir": "Tir",
  "stat.def": "Déf",
  "stat.vit": "Vit",
  "stat.gar": "Gardien",
  "stat.agr": "Agr",
  "stat.forme": "Forme",
  "stat.moral": "Moral",
  "stat.potentiel": "Potentiel",
  "stat.potentiel.estime": "Potentiel estimé",
  "stat.tir.court": "TIR",
  "stat.def.court": "DÉF",
  "stat.vit.court": "VIT",
  "stat.gar.court": "GAR",
  "colonne.pos": "Pos",
  "colonne.nom": "Nom",
  "colonne.age": "Âge",
  "colonne.contrat": "Contrat",
  "colonne.valeur": "Valeur",
  "colonne.joueur": "Joueur",
  "colonne.matchs": "Matchs",
  "colonne.buts": "Buts",
  "colonne.penalites": "Pénalités",
  "colonne.nomClub": "Nom (club)",
  "joueur.indisponible": "indisponible",
  "joueur.indisponible.semaines": {"un": "indisponible {n}j", "autres": "indisponible {n}j"},
  "joueur.contrat.ans": {"un": "{n} an", "autres": "{n} ans"},
  "effectif.nbJoueurs": {"un": "{n} joueur", "autres": "{n} joueurs"},
  "effectif.composition": "Composition : <b>1 gardien</b> (ne tourne pas) + <b>{n} joueur(s) de champ</b> en rotation (●) — de <b>4</b> (une ligne) à <b>{max}</b> (trois lignes). Une ligne : tes quatre meilleurs sur la piste, mais ils s'épuisent — <b>9 points de forme par journée</b>. Deux lignes : <b>4,5</b>. Trois lignes : <b>3</b>, et tout le monde joue — au prix d'un niveau moyen plus bas, et d'un vestiaire nettement plus calme.",
  "effectif.compoAuto": "Compo auto",
  "effectif.intervalle": "Intervalle de changement de ligne :",
  "effectif.intervalle.info": "changements plus fréquents = joueurs plus frais, plus longs = plus d'usure par sortie",
  "effectif.minutes": {"un": "{n} minute", "autres": "{n} minutes"},
  "effectif.minutes1demi": "1,5 minute",
  "effectif.masseSalariale": "Masse salariale : {montantHtml}/match.",
  "effectif.selection": "Sélection des titulaires",
  "effectif.selection.info": "Clique sur une carte pour aligner ou retirer un joueur (● = titulaire, entouré en vert).",
  "effectif.consignes": "Consignes tactiques",
  "effectif.consignes.info": "Ces consignes s'appliquent à tous tes matchs (y compris en direct, modifiable pendant le match).",
  "effectif.style": "Style :",
  "effectif.pressing": "Pressing :",
  "effectif.objectifs": "Objectifs individuels de la saison",
  "effectif.objectifLigne": "{nom} — objectif : {cible} buts cette saison ({buts} inscrits)",
  "effectif.objectifAtteint": "atteint",
  "effectif.stats": "Statistiques de la saison",
  "effectif.complet": "Effectif complet (détails, vente, prêt)",
  "effectif.vendre": "Vendre",
  "effectif.preter": "Prêter",
  "effectif.calmer": "Calmer",
  "effectif.sousConsigne": "Sous consigne",
  "effectif.calmer.info": "Moins de fautes de crosse, mais joue en retrait",
  "tactique.offensif": "Offensif (+attaque, −défense)",
  "tactique.equilibre": "Équilibré",
  "tactique.defensif": "Défensif (+défense, −attaque)",
  "pressing.haut": "Haut (agressif, plus de pénalités)",
  "pressing.moyen": "Moyen",
  "pressing.bas": "Bas (prudent, moins de pénalités)",

  // ---- Classement, Calendrier, Entraînement, staff
  "staff.attaque.label": "Coach attaque",
  "staff.attaque.desc": "Fait progresser le Tir des joueurs de champ",
  "staff.defense.label": "Coach défense",
  "staff.defense.desc": "Fait progresser la Défense des joueurs de champ",
  "staff.physique.label": "Préparateur physique",
  "staff.physique.desc": "Fait progresser la Vitesse de tout l'effectif",
  "staff.gardiens.label": "Coach des gardiens",
  "staff.gardiens.desc": "Fait progresser la stat Gardien des gardiens",
  "staff.discipline.label": "Coach mental / discipline",
  "staff.discipline.desc": "Fait baisser l'Agressivité des joueurs et réduit les pénalités en match",
  "staff.medecin.label": "Médecin du club",
  "staff.medecin.desc": "Réduit le risque et la durée des blessures",
  "staff.recruteur.label": "Recruteur",
  "staff.recruteur.desc": "Réduit le coût des transferts et élargit le vivier de recrutement hors division",
  "staff.specialistes.label": "Coach situations spéciales",
  "staff.specialistes.desc": "Améliore l'efficacité en supériorité numérique et solidifie l'infériorité numérique",
  "staff.requis": "Requis : {quoi}",
  "staff.requis.division": "évoluer au moins en {division}",
  "staff.requis.centre": "centre d'entraînement niveau {n}",
  "staff.note": "note <b>{n}</b>/95",
  "staff.noteCourte": "note <b>{n}</b>",
  "staff.former": "Former (+1) — {prix}",
  "staff.maximum": "Compétence maximale",
  "staff.licencier": "Licencier ({prix})",
  "staff.vacant": "Poste vacant",
  "staff.remplacer": "Remplacer — {prix}",
  "staff.embaucher": "Embaucher — {prix}",
  "staff.frequence": "La note du coach détermine la fréquence des progressions.",
  "staff.mercato": "Mercato des entraîneurs :",
  "staff.mercato.avec": "Mercato des entraîneurs (remplacement inclut l'indemnité de départ) :",
  "entrainement.dispo": "Une séance est disponible",
  "entrainement.deja": "Séance déjà menée cette semaine",
  "entrainement.lancer": "Lancer la séance",
  "entrainement.info": "Une séance supplémentaire, en dehors des journées de championnat, profite surtout à la <b>ligne laissée au repos</b> (les joueurs non alignés) — ils arrivent frais et peuvent se concentrer sur le travail technique. Une seule séance disponible entre deux journées.",
  "entrainement.staff": "Staff technique",
  "entrainement.staff.info": "Recrute tes coachs sur le <b>mercato</b> (note = performance) : jeunes et titulaires progressent plus vite. Certains postes se débloquent progressivement (division + niveau du centre d'entraînement). Tu peux <b>remplacer</b> directement un coach en poste par un meilleur (l'indemnité de départ est incluse dans le prix), ou <b>former</b> ton coach actuel pour lui faire gagner en compétence. Le coach discipline réduit aussi les pénalités en match.",
  "entrainement.derniereSeance": "Dernière séance :",
  "entrainement.derniereHorsMatch": "Dernière séance hors match :",
  "entrainement.aucune": "Aucune progression lors de la dernière journée.",
  "entrainement.aucune.sansCoach": "Aucune progression lors de la dernière journée — embauche un coach pour commencer !",
  "colonne.equipe": "Équipe",
  "colonne.poule": "Poule",
  "colonne.pts": "Pts",
  "colonne.j": "J",
  "colonne.v": "V",
  "colonne.vp": "VP",
  "colonne.dp": "DP",
  "colonne.d": "D",
  "colonne.bp": "BP",
  "colonne.bc": "BC",
  "colonne.diff": "Diff",
  "classement.sousTitre": "Journée {journee} sur {total} · {equipes} équipes",
  "classement.prochaine": "Prochaine rencontre",
  "classement.rang": "{n}<sup>e</sup>",
  "classement.points": "{n} pts",
  "classement.domicile": "à domicile",
  "classement.exterieur": "à l'extérieur",
  "classement.journeeCourte": "J{n}",
  "classement.detail": "Détail chiffré et règles des playoffs",
  "classement.national": "Classement de {division}",
  "classement.national.detail": "{equipes} équipes, {poules} poules",
  "classement.regle.poules": "Chaque poule qualifie ses {n} premiers. Le tableau final réunit huit équipes de toute la division : d'abord les champions de poule, puis les meilleurs suivants.",
  "classement.regle.simple": "Les {n} premiers disputent les playoffs.",
  "classement.regle.format": "Quarts, demi-finales puis finale, chaque tour au meilleur des 3 (aller, retour, match d'appui éventuel). Les deux finalistes montent.",
  "classement.playoffsAVenir": "Les {n} premiers du classement disputeront les playoffs à l'issue de la saison régulière, chaque tour en série aller-retour + match d'appui éventuel (au meilleur des 3).",
  "playoffs.titre": "Playoffs — {division} (Top {n}, séries au meilleur des 3)",
  "playoffs.quarts": "Quarts",
  "playoffs.demies": "Demies",
  "playoffs.finale": "Finale",
  "playoffs.aDeterminer": "à déterminer",
  "playoffs.elimine": "Ton équipe est éliminée — le reste du tableau se résout automatiquement au clic sur le bouton d'action.",
  "calendrier.sousTitre": "{n} journées · aller-retour",
  "calendrier.journee": "Journée {n}",
  "calendrier.aller": "(aller)",
  "calendrier.retour": "(retour)",
  "calendrier.aVenir": "à venir",
  "calendrier.avantMatch": "Avant-match — Prochain adversaire ({ou})",
  "calendrier.bilan": "{v}V {n}N {d}D, forme {forme}% de points pris",
  "calendrier.meilleur": "Meilleur joueur : {qui}",
  "calendrier.danger": "Danger offensif : {qui}",

  // ---- Club et Transferts
  "club.niveau": "Niveau {n}/{max}",
  "club.niveauMax": "Niveau maximum",
  "club.niveauRequis": "Niveau {n} requiert {division}",
  "club.ameliorer": "Améliorer — {prix}",
  "club.classe.titre": "Classement de l'installation — classe {classe}",
  "club.classe.regle": "Le règlement fédéral (art. 2.2.7.2) attache chaque division à une classe de salle.",
  "club.classe.suffisant": "Ton stade de niveau {niveau} est classé <b>{classe}</b> : il autorise déjà la montée en {division}.",
  "club.classe.insuffisant": "Monter en {division} exige la <b>classe {classe}</b>, soit un stade de niveau {requis}. Le tien est au niveau {niveau} : sans travaux, la montée sera refusée.",
  "club.classe.sommet": "Tu es au sommet : la classe A est exigée pour l'Élite et pour toute finale nationale.",
  "club.sousTitre": "Capacité {places} places · {n} chantier(s) disponible(s)",
  "club.capacite": "Capacité actuelle : {placesHtml} places.",
  "club.chantiers": "Chantiers disponibles cette saison : {chantiersHtml} (améliorations infrastructure + loges VIP confondues — les travaux prennent du temps, impossible de tout refaire en une saison).",
  "club.sponsor.actif": "Contrat actif",
  "club.sponsor.resilier": "Résilier",
  "club.sponsor.signer": "Signer",
  "club.recettes.domicile": "Recettes du dernier match ({n} spectateurs)",
  "club.recettes.deplacement": "Recettes du dernier match (déplacement)",
  "club.poste.billetterie": "Billetterie",
  "club.poste.buvette": "Buvette",
  "club.poste.loges": "Loges VIP",
  "club.poste.sponsoring": "Sponsoring",
  "club.poste.tv": "Droits de diffusion",
  "club.poste.communication": "Communication",
  "club.poste.salaires": "Masse salariale (joueurs)",
  "club.poste.staff": "Salaires du staff",
  "club.poste.entretien": "Entretien / frais",
  "club.poste.total": "Total",
  "club.aucuneRecette": "Aucune recette enregistrée pour l'instant.",
  "club.billetterie": "Billetterie & Communication",
  "club.prixBillet": "Prix du billet :",
  "club.prixBillet.info": "prix bas = plus d'affluence, prix haut = plus de recette par personne",
  "club.communication": "Budget communication (par match à domicile) :",
  "club.communication.info": "fait venir plus de monde, mais coûte à chaque match domicile",
  "club.sponsoring": "Sponsoring",
  "club.sponsoring.info": "Les contrats sont <b>cumulatifs</b> : tu peux signer plusieurs sponsors à la fois, chacun débloqué par un niveau de division et d'infrastructure suffisant. Revenu total des sponsors actifs : {totalHtml}.",
  "club.finances": "Finances du dernier match",
  "infra.stade.label": "Tribunes",
  "infra.stade.desc": "Augmente la capacité d'accueil du public",
  "infra.confort.label": "Confort",
  "infra.confort.desc": "Sièges, visibilité : fait revenir plus de spectateurs",
  "infra.buvette.label": "Buvette",
  "infra.buvette.desc": "Augmente les dépenses moyennes par spectateur",
  "infra.centre.label": "Centre d'entraînement",
  "infra.centre.desc": "Accélère toutes les progressions du staff technique",
  "infra.pole.label": "Pôle Espoir",
  "infra.pole.desc": "Forme régulièrement de jeunes recrues à fort potentiel, qui rejoignent directement l'effectif — compense en partie les départs à la retraite",
  "infra.loges.label": "Loges VIP",
  "infra.loges.compte": {"un": "{n}/15 loge", "autres": "{n}/15 loges"},
  "infra.loges.recette": "{montant}/match de recette fixe",
  "infra.loges.requis": "{n}e loge requiert {division}",
  "infra.loges.construire": "Construire une loge — {prix}",
  "poste.tous": "Tous postes",
  "poste.G": "Gardien",
  "poste.D": "Défenseur",
  "poste.A": "Attaquant",
  "tri.ov": "Général",
  "tri.tir": "Tir",
  "tri.def": "Déf",
  "tri.vit": "Vit",
  "tri.gar": "Gardien",
  "tri.val": "Valeur",
  "tri.age": "Âge",
  "tri.agr": "Agressivité",
  "transferts.sousTitre": "Budget {budget} · {n} joueurs sous contrat",
  "transferts.ferme": "Le marché des transferts n'ouvre qu'à partir de la <b>saison 2</b>.",
  "transferts.ferme.info": "Ta première saison se joue avec l'effectif de départ — fais tes preuves, observe qui progresse, et prépare ton budget avant de te lancer sur le marché.",
  "transferts.titre": "Centre de recrutement",
  "transferts.info": "Budget disponible : {budgetHtml}. Achat = valeur +10 % (±premium hors division). Vente (onglet Effectif) = valeur −10 %. Un club peut refuser de vendre ou contre-proposer un prix plus élevé — un bon <b>recruteur</b> limite ce risque et réduit le prix.<br>La pastille à côté de la note générale indique ce que la recrue <b>apporte</b> : l'écart avec le joueur de son poste qu'elle remplacerait, c'est-à-dire le plus faible du groupe.<br>Sous la valeur figure son <b>salaire par journée</b> — le prix d'achat est ponctuel, le salaire se paie à chaque match et pendant toute la durée du contrat.",
  "transferts.portee": "Portée :",
  "transferts.portee.division": "Ma division ({division})",
  "transferts.portee.pyramide": "Toute la pyramide (hors division)",
  "transferts.poste": "Poste :",
  "transferts.trier": "Trier par :",
  "transferts.decroissant": "Décroissant",
  "transferts.croissant": "Croissant",
  "transferts.acheter": "Acheter {prix}",
  "transferts.recruter": "Recruter {prix}",
  "transferts.nonVendable": "non vendable",
  "transferts.aucun": "Aucun joueur pour ce filtre.",

  // ---- rapport de match, sous-menu, objectifs
  "objectif.milieu": "Viser le milieu de tableau",
  "objectif.titre": "Viser le titre de champion des playoffs",
  "objectif.playoffs": "Disputer les playoffs (Top 8)",
  "objectif.maintien": "Assurer le maintien",
  "objectif.maintienDescente": "Assurer le maintien (éviter la descente)",
  "rapport.titre": "Journée {n} — Rapport de match",
  "rapport.prolongation": "Score à égalité à la fin du temps réglementaire — but en or en prolongation.",
  "rapport.autres": "Autres résultats :",
  "rapport.recette": "Recette du match : {montantHtml} (détail dans l'onglet Club)",
  "rapport.aucunePenalite": "Aucune pénalité sifflée.",
  "rapport.aucunBut": "Aucun but…",
  "intro.objectif": "L'objectif de la direction pour cette saison : {objectifHtml}.",

  // ---- fautes, coupe, palmarès, messages
  "faute.retenir": "retenir",
  "faute.accrocher": "accrocher",
  "faute.trebucher": "faire trébucher",
  "faute.obstruction": "obstruction",
  "faute.cinglage": "cinglage",
  "faute.crosseHaute": "crosse haute",
  "faute.piquage": "piquage",
  "faute.retardJeu": "retard de jeu",
  "faute.surnombre": "surnombre",
  "faute.chargeViolente": "charge violente",
  "faute.dureteExcessive": "dureté excessive",
  "faute.chargeBalustrade": "charge contre la balustrade",
  "faute.chargeCrosse": "charge avec la crosse",
  "faute.cinglageBlessure": "cinglage avec blessure",
  "faute.antisportive": "attitude antisportive",
  "faute.contestation": "contestation de décision",
  "faute.conduiteAntisportive": "conduite antisportive",
  "faute.blessureIntentionnelle": "blessure intentionnelle",
  "faute.agression": "agression physique",
  "faute.coupCrosseTete": "coup de crosse dangereux à la tête",
  "penalite.mineure": "Pénalité mineure",
  "penalite.majeure": "Pénalité majeure",
  "penalite.mec": "Pénalité de méconduite (pas d'infériorité, joueur remplacé)",
  "penalite.pm": "Pénalité de match — expulsion",
  "penalite.inferiorite": "Infériorité {n}'.",
  "coupe.nom": "Coupe de France",
  "coupe.tour.finale": "Finale",
  "coupe.tour.demi": "Demi-finale",
  "coupe.tour.quart": "Quart de finale",
  "coupe.tour.seizieme": "Seizième de finale",
  "coupe.tour.trentedeuxieme": "Trente-deuxième de finale",
  "coupe.tour.preliminaire": "Tour préliminaire",
  "coupe.presentation": "Une compétition à élimination directe qui engage <b>toutes les équipes de toutes les divisions nationales</b>, de la N3 à l'Élite — ta division au complet (classement réel de la saison), et les autres générées pour l'occasion. Les meilleures têtes de série sont exemptées du tour préliminaire. Pas de match nul possible.",
  "coupe.rythme": "Les tours se débloquent progressivement au fil des journées de championnat — la coupe est toujours terminée bien avant les demi-finales des playoffs.",
  "coupe.tirageVerrouille": "Tirage au sort disponible à partir de la journée {journee} (actuellement journée {actuelle}).",
  "coupe.lancerTirage": "Lancer le tirage au sort",
  "coupe.aJouer": "à jouer",
  "coupe.prolongationCourte": "(prol.)",
  "coupe.exemptes": "Têtes de série exemptées du tour préliminaire :",
  "coupe.enCours": "en cours",
  "coupe.engagees": "{n} équipes engagées, de la N3 à l'Élite.",
  "coupe.vainqueur": "Vainqueur :",
  "coupe.resultatFinal": "Voir le résultat final",
  "coupe.tourVerrouille": "Prochain tour disponible à partir de la journée {journee} (actuellement journée {actuelle}).",
  "coupe.jouerProchain": "Jouer le prochain match",
  "palmares.montee": "Montée",
  "palmares.descente": "Descente",
  "palmares.maintien": "Maintien",
  "palmares.champion": "champion",
  "palmares.finaliste": "finaliste",
  "palmares.saisons": {"un": "{n} saison", "autres": "{n} saisons"},
  "palmares.montees": {"un": "{n} montée", "autres": "{n} montées"},
  "palmares.saisonEnCours": "Saison {n} en cours",
  "palmares.vide.titre": "Ta première saison est en cours",
  "palmares.vide.note": "Le palmarès se remplit à la fin de chaque saison. Voici ce qui y sera consigné.",
  "palmares.vide.classement": "<b>Classement final</b> — ta place en saison régulière",
  "palmares.vide.playoffs": "<b>Playoffs</b> — jusqu'où tu es allé",
  "palmares.vide.mouvement": "<b>Mouvement</b> — montée, maintien ou descente",
  "palmares.vide.buteur": "<b>Meilleur buteur</b> — celui qui aura porté la saison",
  "messages.compte": {"un": "{n} message", "autres": "{n} messages"},
  "messages.nonLus": {"un": "{n} non lu", "autres": "{n} non lus"},
  "messages.boiteVide": "Boîte vide",
  "messages.vide.titre": "Aucun message pour l'instant",
  "messages.vide.note": "La direction, le staff et les autres clubs t'écriront au fil de la saison.",
  "messages.vide.objectifs": "<b>Objectifs</b> — ce que la direction attend de toi",
  "messages.vide.blessures": "<b>Blessures</b> — qui est indisponible, et pour combien de temps",
  "messages.vide.contrats": "<b>Contrats</b> — les fins de contrat à anticiper",
  "messages.vide.sponsors": "<b>Sponsors</b> — les offres qui se débloquent",

  // ---- tutoriel guidé
  "tuto.passer": "Passer le tutoriel",
  "tuto.continuer": "Continuer",
  "tuto.commencer": "Commencer",
  "tuto.compris": "Compris",
  "tuto.terminer": "Terminer",
  "tuto.aller": "Touche <b>{ecran}</b>.",
  "tuto.tour.titre": "Petit tour du propriétaire",
  "tuto.tour.texte": "Je te montre les écrans un par un, jusqu'à ton premier match. C'est court, et tu peux passer quand tu veux.",
  "tuto.effectif.texte": "Tu y es déjà : c'est ta feuille de match. Tu y choisis ton gardien et tes joueurs de champ, et tu vois qui est en forme.",
  "tuto.composer.titre": "Composer son équipe",
  "tuto.composer.texte": "Un gardien et quatre joueurs de champ sur la piste, comme le veut le roller in line hockey. Les autres tournent : plus tu fais tourner, moins tes joueurs s'usent.",
  "tuto.entrainement.texte": "Touche <b>{ecran}</b>. C'est ici que ton effectif progresse — ou stagne, si tu n'as personne pour l'encadrer.",
  "tuto.coach.titre": "Ton premier coach",
  "tuto.coach.texte": "Embauche un coach. Sans staff, <b>aucune progression</b> : la séance est même refusée. Je te montre le moins cher, mais tu peux en choisir un autre.",
  "tuto.seance.titre": "La première séance",
  "tuto.seance.texte": "Lance la séance. Une par semaine, entre deux journées — ce sont surtout les joueurs <b>laissés au repos</b> qui en profitent, ils arrivent frais.",
  "tuto.lireClassement.titre": "Lire le classement",
  "tuto.lireClassement.texte": "Barème FFRS : <b>3</b> points la victoire, <b>2</b> une victoire en prolongation, <b>1</b> une défaite en prolongation, <b>0</b> une défaite. À égalité, c'est la différence de buts qui départage.",
  "tuto.construire.titre": "Construire son club",
  "tuto.construire.texte": "Stade, confort, buvette, centre d'entraînement, sponsors. Attention : <b>monter de division exige une salle classée</b> — sans les travaux, la montée est refusée même en gagnant. Deux chantiers par saison, pas plus.",
  "tuto.reste.titre": "Tout le reste",
  "tuto.reste.tiroir": "Touche <b>{plus}</b> : transferts, calendrier, Coupe de France, messages, historique, aide et options y sont rangés.",
  "tuto.reste.large": "Ton écran est large : tous les écrans tiennent dans la barre — transferts, calendrier, Coupe de France, messages, historique, aide et options. Sur téléphone, les derniers passent dans un tiroir « Plus ».",
  "tuto.tiroir.titre": "Referme le tiroir",
  "tuto.tiroir.texte": "Referme le tiroir : tire la poignée vers le bas, ou touche n'importe où au-dessus du panneau.",
  "tuto.jouer.titre": "À l'eau",
  "tuto.jouer.texte": "Touche <b>{bouton}</b>. Tu peux regarder le match se dérouler, ou passer directement au résultat.",
  "tuto.fin.titre": "À toi de jouer maintenant !",
  "tuto.fin.texte": "Tu as tout ce qu'il faut : composer, entraîner, construire, recruter. Pars du Régional et monte aussi haut que tu peux — l'Élite est à cinq divisions."
});

if (typeof PIECES_CHARGEES === 'object') PIECES_CHARGEES.textesfr = true;
