// textes-en.js — the game text in English
//
// Traduction. Ce qui n'est PAS traduit, et ne le sera pas : noms de joueurs, de clubs,
// de villes, de sponsors, prénoms de coachs. Ce sont des noms propres.
//
// Chargé par un <script> CLASSIQUE, pas un module ES : ceux-ci sont bloqués par CORS sous
// file://, et le jeu doit pouvoir s'ouvrir par double-clic.
//
// Une clé peut porter une chaîne, ou { un, autres } quand un pluriel est en jeu. Le
// français met 0 ET 1 au singulier, l'anglais met 0 au pluriel : c'est `REGLE_PLURIEL` qui
// tranche, pas ce fichier.
//
// Les marqueurs {nom} sont substitués par `T(cle, params)`. L'échappement reste à
// l'appelant : `T('cle', { nom: escHtml(p.nom) })`.

// Pas de garde `typeof` autour de cette affectation : `TEXTES` est déclaré dans le bloc
// d'amorçage de la page, donc toujours là. Un garde ferait échouer le chargement EN SILENCE
// si l'ordre changeait un jour — et c'est exactement le défaut qu'on a payé une fois.
Object.assign(TEXTES.en, {
  "ecran.effectif.label": "Squad",
  "ecran.effectif.court": "Squad",
  "ecran.club.label": "Club",
  "ecran.club.court": "Club",
  "ecran.entrainement.label": "Training",
  "ecran.entrainement.court": "Train.",
  "ecran.classement.label": "Standings",
  "ecran.classement.court": "Table",
  "ecran.calendrier.label": "Fixtures",
  "ecran.calendrier.court": "Fixtures",
  "ecran.transferts.label": "Transfers",
  "ecran.transferts.court": "Transf.",
  "ecran.inbox.label": "Messages",
  "ecran.inbox.court": "Messages",
  "ecran.historique.label": "History",
  "ecran.historique.court": "History",
  "ecran.coupe.label": "Cup",
  "ecran.coupe.court": "Cup",
  "ecran.aide.label": "Help",
  "ecran.aide.court": "Help",
  "ecran.options.label": "Settings",
  "ecran.options.court": "Settings",
  "reglages.langue.titre": "Language",
  "reglages.langue.note": "The whole game follows this choice. Player, club and town names stay as they are — they are proper nouns.",
  "reglages.son.titre": "Sound",
  "reglages.son.note": "The music changes with the screen. It stops on its own when you leave the app.",
  "reglages.son.active": "On",
  "reglages.son.coupee": "Muted",
  "reglages.son.volume": "Volume",
  "reglages.partie.titre": "Current game",
  "reglages.partie.note": "Go back to the title screen to switch slot or start another game. Yours is saved automatically — you will find it exactly as you left it.",
  "reglages.partie.retour": "Back to title screen",
  "reglages.partie.confirmer": "Back to title",
  "reglages.partie.question": "Go back to the title screen?\\n\\nYour game is saved — you will find it in this slot.",
  "reglages.barre.titre": "Bottom bar",
  "reglages.barre.note": "Choose which screens appear directly, and in what order. The rest stay available under the « More » button.",
  "reglages.barre.retirer": "Remove {ecran} from the bar",
  "reglages.barre.ajouter": "Add {ecran} to the bar",
  "reglages.barre.capacite": {"un": "This screen shows <b>{n} entry</b> at its current width ({largeur} px).", "autres": "This screen shows <b>{n} entries</b> at its current width ({largeur} px)."},
  "reglages.barre.reste": {"un": "The last screen is under « More ».", "autres": "The other {n} screens are under « More »."},
  "reglages.barre.tout": "Everything fits in the bar, the « More » button disappears.",
  "reglages.barre.elargis": "Widen the window and the bar fills out by itself.",
  "reglages.version": "version {n}",

  // ---- tranche 2 : bandeau, bouton d'action, tiroir
  "bandeau.saison": "season",
  "bandeau.journee": "matchday",
  "bandeau.budget": "Budget",
  "bandeau.objectif": "Target",
  "bandeau.direction": "Board",
  "bandeau.rang": "{rang} of {total}",
  "nav.plus": "More",
  "action.journee": "Play matchday {n}",
  "action.coupe.tirage": "Draw the Coupe de France",
  "action.coupe.resultats": "Coupe de France results",
  "action.coupe.jouer": "Play the Coupe de France tie",
  "action.playoffs.lancer": "Start the playoffs (Top 8)",
  "action.playoffs.final": "See the final playoff result",
  "action.playoffs.quart": "Play a quarter-final",
  "action.playoffs.demi": "Play a semi-final",
  "action.playoffs.finale": "Play a final",
  "action.bilan": "End-of-season review",

  // ---- courrier
  "courrier.date": "Season {saison} · matchday {journee}",
  "courrier.ta-reponse": "Your answer: {dit}",
  "courrier.brouille.deplace": "Your answer: {dit} {nom} moves to line {ligne}.",
  "courrier.brouille.impossible": "No line can take him. He stays where he is.",
  "courrier.vestiaire.partir.titre": "🚪 {nom} wants out",
  "courrier.vestiaire.tete.titre": "😠 {nom} is sulking",
  "courrier.vestiaire.partir.corps": {"un": "{portraitHtml}{nom} came to see me. He has had enough of this situation and asks to leave the club. {n} game played this season.", "autres": "{portraitHtml}{nom} came to see me. He has had enough of this situation and asks to leave the club. {n} games played this season."},
  "courrier.vestiaire.tete.corps": {"un": "{portraitHtml}{nom} is still fuming. {n} game played this season, and he reckons he is worth more than that.", "autres": "{portraitHtml}{nom} is still fuming. {n} games played this season, and he reckons he is worth more than that."},
  "courrier.engagement.tenu.titre": "🤝 Promise kept — {nom}",
  "courrier.engagement.rompu.titre": "💥 Promise broken — {nom}",
  "courrier.engagement.chiffre.tenu": "{nom} played {presences} of the last {journees} matchdays, as promised. He will not forget it.",
  "courrier.engagement.chiffre.rompu": "{nom} only played {presences} times out of {journees}. He had my word. He is asking to leave.",
  "courrier.engagement.parole.tenue": "{nom} is back at work. The talk got through.",
  "courrier.engagement.parole.rompue": "{nom} saw none of what I promised him. He will never believe me again.",
  "courrier.objectifJoueur.atteint.titre": "🎯 Personal target met",
  "courrier.objectifJoueur.manque.titre": "📉 Personal target missed",
  "courrier.objectifJoueur.atteint.corps": "{nom} met his target of {cible} goals ({buts} scored) — morale up.",
  "courrier.objectifJoueur.manque.corps": "{nom} only scored {buts} against a target of {cible} — a little disappointed.",
  "courrier.coupe.titre": "🏆 Coupe de France",
  "courrier.coupe.auto": "The cup was settled automatically before the playoffs began (winner: {vainqueur}).",
  "courrier.coupe.tirage.tard": "The draw is done: <b>{clubs} clubs entered</b>, from Régional to Élite — one per association, as the rules require. Your level means you enter later, when only {entree} teams are left. Seeded no. {tete}.",
  "courrier.coupe.tirage.premier": "The draw is done: <b>{clubs} clubs entered</b>, from Régional to Élite — one per association, as the rules require. You enter in the first round. Seeded no. {tete}.",
  "courrier.coupe.tirage.exempt": "The draw is done: <b>{clubs} clubs entered</b>, from Régional to Élite — one per association, as the rules require. You enter in the first round, and you have a bye. Seeded no. {tete}.",
  "courrier.coupe.fin.titre": "🏆 Coupe de France over",
  "courrier.coupe.fin.gagnee": "Your team wins the Coupe de France, against {equipes} teams entered! Prize: {prime}.",
  "courrier.coupe.fin.autre": "{nom} ({origine}) wins the Coupe de France this season.",
  "courrier.effectif.grave.titre": "🚨 The board is worried about the squad",
  "courrier.effectif.leger.titre": "📉 The board on the squad",
  "courrier.effectif.grave.corps": "A word on the group before the season starts. The squad averages <b>{force}</b>, while {division} sits around <b>{milieu}</b>: <b>{ecart} points behind</b>. At that gap, training alone will not save the season — it gains a few points a year, not ten. The <b>transfer market</b> is the only immediate lever: a few well-chosen signings beat a season of sessions.",
  "courrier.effectif.leger.corps": "A word on the group before the season starts. The squad averages <b>{force}</b>, while {division} sits around <b>{milieu}</b>: <b>{ecart} points behind</b>. Training can close that in a season or two with good staff. One or two signings would speed it up.",
  "courrier.stade.point.titre": "🏗️ The board on the facilities",
  "courrier.stade.point.corps": "A word before the season starts. {detailHtml} On the court, nothing stops us aiming higher — on paper, plenty does.",
  "courrier.stade.refus1.titre": "🚧 We have already been denied a promotion",
  "courrier.stade.refus1.corps": "Last season we won on the court and lost at the desk: promotion was <b>denied</b> for want of a rated venue. {detailHtml}{chiffrageHtml} Starting another season on these terms would mean playing for nothing.",
  "courrier.stade.refusN.titre": "🛑 {n} promotions denied — the venue is THE priority",
  "courrier.stade.refusN.corps": "<b>{n} times</b> we earned promotion on the court, <b>{n} times</b> it was denied for the same reason. {detailHtml}{chiffrageHtml} Until the venue is rated, every euro spent on the squad is money that will not get us up.",
  "courrier.stade.encore.titre": "🛑 Promotion will slip away again",
  "courrier.stade.insiste.titre": "⚠️ The board insists on the building work",
  "courrier.stade.encore.corps": {"un": "We are {rang}{ordinal} and promotion is taking shape. It would be <b>denied as things stand</b>. {detailHtml} That is exactly what has already happened to us {refus} times. {n} matchday left to act.", "autres": "We are {rang}{ordinal} and promotion is taking shape. It would be <b>denied as things stand</b>. {detailHtml} That is exactly what has already happened to us {refus} times. {n} matchdays left to act."},
  "courrier.stade.insiste.corps": "We are {rang}{ordinal} and promotion is taking shape. It would be <b>denied as things stand</b>. {detailHtml}",
  "courrier.stade.homologue.titre": "✅ Venue approved",
  "courrier.stade.homologue.corps": "The work has been signed off. Our venue is now <b>class {classe}</b>: it meets the requirements for {division}. Promotion now depends on results alone.",
  "courrier.objectif.fixe.titre": "📋 The board sets its target",
  "courrier.objectif.fixe.corps": "For this season in {division}, the board sets the target: {objectif}.",
  "courrier.objectif.atteint.titre": "✅ Target met",
  "courrier.objectif.manque.titre": "⚠️ Target missed",
  "courrier.objectif.atteint.corps": "The board is satisfied: target « {objectif} » met! Confidence bonus: {prime}.",
  "courrier.objectif.manque.corps": "The board is disappointed: target « {objectif} » not met (board confidence down: {confiance}/100).",
  "courrier.accession.decrochee.titre": "🎟️ Promotion play-off won",
  "courrier.accession.phase.titre": "🎟️ Promotion play-off",
  "courrier.accession.pasDeTicket": {"un": "{rang}<sup>th</sup> in the group: no ticket for the promotion play-off. Our league sends only <b>{n}</b> club, taken from the top four (art. 9.3 B). We must finish higher.", "autres": "{rang}<sup>th</sup> in the group: no ticket for the promotion play-off. Our league sends only <b>{n}</b> clubs, taken from the top four (art. 9.3 B). We must finish higher."},
  "courrier.accession.gagnee": "Promotion tournament won: <b>{place}<sup>th</sup></b> of the {places} national places. Nationale 3 next.",
  "courrier.accession.perdue": "We played the promotion tournament, but the place slips away: only <b>{places} places</b> are up for grabs in the whole country (art. 9.3 C). Winning your group is not enough — you must come through the tournament.",
  "courrier.carriere.titre": "🎽 End of a national career",
  "courrier.carriere.corps": "{portraitHtml}{nom} ({age}) is leaving the national league.{statsHtml} He fully intends to keep skating at regional level, more quietly. Thanks for everything!",
  "courrier.espoir.titre": "🌟 New prospect",
  "courrier.espoir.corps": "{portraitHtml}{nom} ({age}, {poste}) comes out of the academy and signs his first professional contract with the club.",
  "courrier.prolongation.titre": "Contract extended",
  "courrier.prolongation.corps": {"un": "{portraitHtml}{nom} has extended his contract by {n} season.", "autres": "{portraitHtml}{nom} has extended his contract by {n} seasons."},
  "courrier.finContrat.titre": "Contract over",
  "courrier.finContrat.corps": "{portraitHtml}{nom} has left the club, his contract having run out (free agent).",
  "courrier.retourPret.titre": "🔄 Back from loan",
  "courrier.retourPret.corps": "{nom} is back from his loan.",
  "courrier.pret.titre": "🔄 Loan",
  "courrier.pret.corps": "{nom} is loaned out for the rest of the season. He will be back in the off-season.",

  // ---- presse, vestiaire, événements
  "presse.accroche.elogieux.0": "📰 A statement",
  "presse.accroche.elogieux.1": "📰 Style and substance",
  "presse.accroche.elogieux.2": "📰 A masterclass",
  "presse.accroche.elogieux.3": "📰 Steamrollered",
  "presse.accroche.neutre.0": "📰 A win that counts",
  "presse.accroche.neutre.1": "📰 Job done",
  "presse.accroche.neutre.2": "📰 Within themselves",
  "presse.accroche.severe.0": "📰 A night to forget",
  "presse.accroche.severe.1": "📰 The fall",
  "presse.accroche.severe.2": "📰 Nothing worked",
  "presse.accroche.severe.3": "📰 A rude awakening awaits",
  "presse.corps.exploit": "<i>{journal}</i> — {nous} {mien}–{sien} {eux}. Nobody saw that result coming against the league leaders.",
  "presse.corps.contreperf": "<i>{journal}</i> — {nous} {mien}–{sien} {eux}. A defeat to the bottom club, hard to explain away.",
  "presse.corps.large": "<i>{journal}</i> — {nous} {mien}–{sien} {eux}. The margin says everything about the control on show.",
  "presse.corps.lourde": "<i>{journal}</i> — {nous} {mien}–{sien} {eux}. The scoreline is harsh, but it is not stolen.",
  "presse.corps.simple": "<i>{journal}</i> — {nous} {mien}–{sien} {eux}.",
  "presse.corps.exploit.triple": "<i>{journal}</i> — {nous} {mien}–{sien} {eux}. Nobody saw that result coming against the league leaders. <b>{triple}</b> helps himself to a hat-trick.",
  "presse.corps.contreperf.triple": "<i>{journal}</i> — {nous} {mien}–{sien} {eux}. A defeat to the bottom club, hard to explain away. <b>{triple}</b> still helps himself to a hat-trick.",
  "presse.corps.large.triple": "<i>{journal}</i> — {nous} {mien}–{sien} {eux}. The margin says everything about the control on show. <b>{triple}</b> helps himself to a hat-trick.",
  "presse.corps.lourde.triple": "<i>{journal}</i> — {nous} {mien}–{sien} {eux}. The scoreline is harsh, but it is not stolen. <b>{triple}</b> still helps himself to a hat-trick.",
  "presse.corps.simple.triple": "<i>{journal}</i> — {nous} {mien}–{sien} {eux}. <b>{triple}</b> helps himself to a hat-trick.",
  "reponse.presse.mesure.label": "Stay measured",
  "reponse.presse.mesure.dit": "“One win, nothing more. We are back at work tomorrow.”",
  "reponse.presse.feliciter.label": "Praise the group",
  "reponse.presse.feliciter.dit": "“They were immense. Tonight belongs to them.”",
  "reponse.presse.concentre.label": "Stay focused",
  "reponse.presse.concentre.dit": "“We take the points and move on. Nothing is settled.”",
  "reponse.presse.caractere.label": "Praise their character",
  "reponse.presse.caractere.dit": "“They did not panic. That is what I take from it.”",
  "reponse.presse.defendre.label": "Defend my players",
  "reponse.presse.defendre.dit": "“Nobody hid out there. The group is not the problem.”",
  "reponse.presse.assumer.label": "Take the blame publicly",
  "reponse.presse.assumer.dit": "“That was unworthy of this club. Starting with me.”",
  "reponse.vestiaire.rassurer.label": "Reassure him",
  "reponse.vestiaire.rassurer.dit": "“You matter to this group. Keep a cool head.”",
  "reponse.vestiaire.promettre.label": "Promise him game time",
  "reponse.vestiaire.promettre.dit": "“You will play. I am telling you to your face, not into thin air.”",
  "reponse.vestiaire.ignorer.label": "Say nothing",
  "reponse.vestiaire.ignorer.dit": "“…”",
  "reponse.brouille.separer.label": "Split their lines",
  "reponse.brouille.separer.dit": "“They will not play together again.”",
  "reponse.brouille.laisser.label": "Let them sort it out",
  "reponse.brouille.laisser.dit": "“They are adults. Let them talk.”",
  "evenement.accrochage.titre": "🔥 Row in the changing room",
  "evenement.accrochage.corps": "{a} and {b} had words after the game. They play on the same line, and it shows now.",
  "evenement.parrainage.titre": "🧭 {ancien} takes {jeune} under his wing",
  "evenement.parrainage.corps": "The veteran spent the week working with the youngster. It will show on the court, and it already shows in the changing room.",
  "evenement.jalousie.titre": "😤 {frustre} is struggling with the competition",
  "evenement.jalousie.corps": "He reckons he is worth more than {rival}, who plays in his place. The mood between them is suffering.",
  "evenement.soiree.titre": "🎉 Club night",
  "evenement.soiree.corps": "Everyone was there — players, volunteers and committee. Nights like these are what hold a group together over a season.",

  // ---- écran Effectif, cartes et tableau
  "stat.general": "Overall",
  "stat.tir": "Shot",
  "stat.def": "Def",
  "stat.vit": "Speed",
  "stat.gar": "Keeper",
  "stat.agr": "Agg",
  "stat.forme": "Fitness",
  "stat.moral": "Morale",
  "stat.potentiel": "Potential",
  "stat.potentiel.estime": "Estimated potential",
  "stat.tir.court": "SHT",
  "stat.def.court": "DEF",
  "stat.vit.court": "SPD",
  "stat.gar.court": "GK",
  "colonne.pos": "Pos",
  "colonne.nom": "Name",
  "colonne.age": "Age",
  "colonne.contrat": "Contract",
  "colonne.valeur": "Value",
  "colonne.joueur": "Player",
  "colonne.matchs": "Games",
  "colonne.buts": "Goals",
  "colonne.penalites": "Penalties",
  "colonne.nomClub": "Name (club)",
  "joueur.indisponible": "out",
  "joueur.indisponible.semaines": {"un": "out {n}d", "autres": "out {n}d"},
  "joueur.contrat.ans": {"un": "{n} year", "autres": "{n} years"},
  "effectif.nbJoueurs": {"un": "{n} player", "autres": "{n} players"},
  "effectif.composition": "Line-up: <b>1 keeper</b> (no rotation) + <b>{n} outfield player(s)</b> rotating (●) — from <b>4</b> (one line) to <b>{max}</b> (three lines). One line: your best four on the court, but they burn out — <b>9 fitness points a matchday</b>. Two lines: <b>4.5</b>. Three lines: <b>3</b>, and everyone plays — at the cost of a lower average level, and a far calmer changing room.",
  "effectif.compoAuto": "Auto line-up",
  "effectif.intervalle": "Line change interval:",
  "effectif.intervalle.info": "more frequent changes = fresher players, longer shifts = more wear per stint",
  "effectif.minutes": {"un": "{n} minute", "autres": "{n} minutes"},
  "effectif.minutes1demi": "1.5 minutes",
  "effectif.masseSalariale": "Wage bill: {montantHtml}/game.",
  "lignes.titre": "The lines",
  "lignes.info": "Who skates with whom. Bonds only count between players on the same line.",
  "lignes.ligne": "L{n}",
  "poste.G.court": "GK",
  "poste.D.court": "DEF",
  "poste.A.court": "FWD",
  "lignes.compo": "{d} def · {a} fwd",
  "lignes.banc": "BENCH",
  "lignes.vide": "no player",
  "lignes.bancCompte": {"un": "{n} player available", "autres": "{n} players available"},
  "entente.titre": "Bonds and tensions",
  "entente.info": "Everything brewing in the locker room, including what your inbox told you.",
  "entente.aucune": "Nothing notable yet: bonds are built by playing together.",
  "entente.compte": "counts on L{n}",
  "entente.sansEffet": "no effect — different lines",
  "entente.bonne.1": "get along well",
  "entente.bonne.2": "close partners",
  "entente.bonne.3": "inseparable",
  "entente.mauvaise.1": "a chill",
  "entente.mauvaise.2": "tension",
  "entente.mauvaise.3": "not speaking",
  "ligne.editer.info": "Drop a player, or pick one from those available.",
  "ligne.alignes": "On the line",
  "ligne.disponibles": "Available",
  "ligne.retirer": "Drop",
  "ligne.aligner": "Select",
  "ligne.remplacer": "Swap in…",
  "ligne.remplacerQui": "Who comes off to make room for {nom}?",
  "ligne.termine": "Done",
  "ligne.annuler": "Cancel",
  "ligne.surLeBanc": "bench",
  "ligne.aucunDispo": "Nobody available.",
  "ligne.pleine": {"un": "A line holds at most {n} player.", "autres": "A line holds at most {n} players."},
  "ligne.plafond": {"un": "At most {n} outfield player on the sheet.", "autres": "At most {n} outfield players on the sheet."},
  "ligne.blesse": "{nom} is unavailable.",
  "ligne.pasGardien": "Only a goalkeeper can fill this spot.",
  "ligne.gardienHorsLigne": "The goalkeeper doesn't rotate: he has his own spot.",
  "coupe.exempte.titre": "Bye this round",
  "coupe.exempte.corps": "Your club does not play the {tour}: it gets a bye and goes straight through to the next round.",
  "coupe.exempte.regle": "When the number of entrants is not a power of two, the highest-ranked clubs skip a round to bring the bracket back to size (art. 7.2 C).",
  "rapport.titreCoupe": "{tour} · Coupe de France",
  "ligne.faireSortir": "Take off",
  "compo.complete": {"un": "Incomplete line: {n} player pulled from the bench.", "autres": "Incomplete lines: {n} players pulled from the bench."},
  "compo.completeHorsNorme": {"un": "Line filled with {n} player: no balance left to keep.", "autres": "Lines filled with {n} players: no balance left to keep."},
  "compo.dissoute": {"un": "{n} line disbanded — not enough players to fill it.", "autres": "{n} lines disbanded — not enough players to fill them."},
  "compo.effectifCourt": {"un": "Squad too short: taking the floor with {n} outfield player.", "autres": "Squad too short: taking the floor with {n} outfield players."},
  "forfait.titre": "Not enough players",
  "forfait.constat": "You can only field {champ} outfield player(s) and {gardiens} goalkeeper(s). The rules require {seuil} + 1.",
  "forfait.consequences": "Playing anyway means a forfeit:",
  "forfait.csq.score": "match lost <b>5-0</b> by default",
  "forfait.csq.points": "<b>−2 points</b> in the table",
  "forfait.csq.adverse": "3 points to your opponent, without playing",
  "forfait.article": "FFRS sporting rules, art. 6.1.1 A and 11.3.1.4.",
  "forfait.alternative": "You can go sign someone in the Transfers tab first — the matchday will wait.",
  "forfait.declarer": "Declare forfeit",
  "forfait.renoncer": "Sign someone first",
  "rapport.forfait": "Forfeit — match lost 5-0 by default, −2 points.",
  "tuto.attente": "⌛ The tutorial is waiting for you.",
  "entente.neuve": "new",
  "entente.bougee": "changed",
  "entente.nouvelles": {"un": "{n} update", "autres": "{n} updates"},
  "joueur.retourLe": "back on {date}",
  "entrainement.dispoN": {"un": "{n} session before the match on {date}", "autres": "{n} sessions before the match on {date}"},
  "calendrier.prochain": "Next match {date}",
  "calendrier.dansJours": {"un": "in {n} day", "autres": "in {n} days"},
  "calendrier.seances": {"un": "{n} training session until then", "autres": "{n} training sessions until then"},
  "effectif.selection": "Starting line-up",
  "effectif.selection.info": "Tap a card to select or drop a player (● = starter, outlined in green).",
  "effectif.consignes": "Tactical instructions",
  "effectif.consignes.info": "These instructions apply to every game (including live matches, where you can change them mid-game).",
  "effectif.style": "Style:",
  "effectif.pressing": "Pressing:",
  "effectif.objectifs": "Personal targets for the season",
  "effectif.objectifLigne": "{nom} — target: {cible} goals this season ({buts} scored)",
  "effectif.objectifAtteint": "met",
  "effectif.stats": "Season statistics",
  "effectif.complet": "Full squad (details, sale, loan)",
  "effectif.vendre": "Sell",
  "effectif.preter": "Loan out",
  "effectif.calmer": "Calm down",
  "effectif.sousConsigne": "Under orders",
  "effectif.calmer.info": "Fewer stick fouls, but plays deeper",
  "tactique.offensif": "Attacking (+attack, −defence)",
  "tactique.equilibre": "Balanced",
  "tactique.defensif": "Defensive (+defence, −attack)",
  "pressing.haut": "High (aggressive, more penalties)",
  "pressing.moyen": "Medium",
  "pressing.bas": "Low (cautious, fewer penalties)",

  // ---- Classement, Calendrier, Entraînement, staff
  "staff.attaque.label": "Attack coach",
  "staff.attaque.desc": "Improves the Shot of outfield players",
  "staff.defense.label": "Defence coach",
  "staff.defense.desc": "Improves the Defence of outfield players",
  "staff.physique.label": "Fitness coach",
  "staff.physique.desc": "Improves the Speed of the whole squad",
  "staff.gardiens.label": "Goalkeeping coach",
  "staff.gardiens.desc": "Improves the Keeper rating of goalkeepers",
  "staff.discipline.label": "Mental / discipline coach",
  "staff.discipline.desc": "Lowers player Aggression and cuts penalties in games",
  "staff.medecin.label": "Club doctor",
  "staff.medecin.desc": "Reduces the risk and length of injuries",
  "staff.recruteur.label": "Scout",
  "staff.recruteur.desc": "Cuts transfer costs and widens the recruitment pool beyond the division",
  "staff.specialistes.label": "Special teams coach",
  "staff.specialistes.desc": "Improves power-play efficiency and firms up the penalty kill",
  "staff.requis": "Requires: {quoi}",
  "staff.requis.division": "playing at least in {division}",
  "staff.requis.centre": "training centre level {n}",
  "staff.note": "rating <b>{n}</b>/95",
  "staff.noteCourte": "rating <b>{n}</b>",
  "staff.former": "Train (+1) — {prix}",
  "staff.maximum": "Maximum skill",
  "staff.licencier": "Dismiss ({prix})",
  "staff.vacant": "Post vacant",
  "staff.remplacer": "Replace — {prix}",
  "staff.embaucher": "Hire — {prix}",
  "staff.frequence": "The coach rating sets how often players improve.",
  "staff.mercato": "Coaching market:",
  "staff.mercato.avec": "Coaching market (replacing includes the severance payment):",
  "entrainement.dispo": "A session is available",
  "entrainement.deja": "Session already held this week",
  "entrainement.lancer": "Start the session",
  "entrainement.info": "An extra session, outside matchdays, mostly benefits the <b>rested line</b> (players left out) — they turn up fresh and can focus on technical work. Only one session between two matchdays.",
  "entrainement.staff": "Coaching staff",
  "entrainement.staff.info": "Hire your coaches on the <b>market</b> (rating = performance): young players and starters improve faster. Some posts unlock gradually (division + training centre level). You can <b>replace</b> a coach in post with a better one directly (the severance is included in the price), or <b>train</b> your current coach to raise his skill. The discipline coach also cuts penalties in games.",
  "entrainement.derniereSeance": "Last session:",
  "entrainement.derniereHorsMatch": "Last non-matchday session:",
  "entrainement.aucune": "No improvement on the last matchday.",
  "entrainement.aucune.sansCoach": "No improvement on the last matchday — hire a coach to get started!",
  "colonne.equipe": "Team",
  "colonne.poule": "Group",
  "colonne.pts": "Pts",
  "colonne.j": "P",
  "colonne.v": "W",
  "colonne.vp": "OTW",
  "colonne.dp": "OTL",
  "colonne.d": "L",
  "colonne.bp": "GF",
  "colonne.bc": "GA",
  "colonne.diff": "GD",
  "classement.sousTitre": "Matchday {journee} of {total} · {equipes} teams",
  "classement.prochaine": "Next fixture",
  "classement.rang": "{n}<sup>th</sup>",
  "classement.points": "{n} pts",
  "classement.domicile": "at home",
  "classement.exterieur": "away",
  "classement.journeeCourte": "MD{n}",
  "classement.detail": "Full figures and playoff rules",
  "classement.national": "{division} national table",
  "classement.national.detail": "{equipes} teams, {poules} groups",
  "classement.regle.poules": "Each group qualifies its top {n}. The final bracket brings together eight teams from across the division: group champions first, then the best of the rest.",
  "classement.regle.simple": "The top {n} go through to the playoffs.",
  "classement.regle.format": "Quarter-finals, semi-finals then the final, each round best of 3 (home, away, decider if needed). Both finalists go up.",
  "classement.playoffsAVenir": "The top {n} in the table will play the playoffs at the end of the regular season, each round a home-and-away series plus a decider if needed (best of 3).",
  "playoffs.titre": "Playoffs — {division} (Top {n}, best-of-3 series)",
  "playoffs.quarts": "Quarters",
  "playoffs.demies": "Semis",
  "playoffs.finale": "Final",
  "playoffs.aDeterminer": "to be decided",
  "playoffs.elimine": "Your team is out — the rest of the bracket is settled automatically when you press the action button.",
  "calendrier.sousTitre": "{n} matchdays · home and away",
  "calendrier.journee": "Matchday {n}",
  "calendrier.aller": "(home leg)",
  "calendrier.retour": "(away leg)",
  "calendrier.aVenir": "up next",
  "calendrier.avantMatch": "Pre-match — Next opponent ({ou})",
  "calendrier.bilan": "{v}W {n}D {d}L, form {forme}% of points taken",
  "calendrier.meilleur": "Best player: {qui}",
  "calendrier.danger": "Attacking threat: {qui}",

  // ---- Club et Transferts
  "club.niveau": "Level {n}/{max}",
  "club.niveauMax": "Maximum level",
  "club.niveauRequis": "Level {n} requires {division}",
  "club.ameliorer": "Upgrade — {prix}",
  "club.classe.titre": "Venue rating — class {classe}",
  "club.classe.regle": "Federal rules (art. 2.2.7.2) tie each division to a venue class.",
  "club.classe.suffisant": "Your level {niveau} venue is rated <b>{classe}</b>: it already allows promotion to {division}.",
  "club.classe.insuffisant": "Going up to {division} requires <b>class {classe}</b>, meaning a level {requis} venue. Yours is level {niveau}: without building work, promotion will be denied.",
  "club.classe.sommet": "You are at the top: class A is required for Élite and for any national final.",
  "club.sousTitre": "Capacity {places} seats · {n} project(s) available",
  "club.capacite": "Current capacity: {placesHtml} seats.",
  "club.chantiers": "Projects available this season: {chantiersHtml} (infrastructure upgrades and VIP boxes combined — building takes time, you cannot redo everything in one season).",
  "club.sponsor.actif": "Contract active",
  "club.sponsor.resilier": "Terminate",
  "club.sponsor.signer": "Sign",
  "club.recettes.domicile": "Last game revenue ({n} spectators)",
  "club.recettes.deplacement": "Last game revenue (away)",
  "club.poste.billetterie": "Ticketing",
  "club.poste.buvette": "Refreshments",
  "club.poste.loges": "VIP boxes",
  "club.poste.sponsoring": "Sponsorship",
  "club.poste.tv": "Broadcast rights",
  "club.poste.communication": "Marketing",
  "club.poste.salaires": "Wage bill (players)",
  "club.poste.staff": "Staff wages",
  "club.poste.entretien": "Upkeep / overheads",
  "club.poste.total": "Total",
  "club.aucuneRecette": "No revenue recorded yet.",
  "club.billetterie": "Ticketing & Marketing",
  "club.prixBillet": "Ticket price:",
  "club.prixBillet.info": "low price = bigger crowd, high price = more revenue per head",
  "club.communication": "Marketing budget (per home game):",
  "club.communication.info": "brings more people in, but costs at every home game",
  "club.sponsoring": "Sponsorship",
  "club.sponsoring.info": "Contracts are <b>cumulative</b>: you can sign several sponsors at once, each unlocked by a high enough division and facility level. Total income from active sponsors: {totalHtml}.",
  "club.finances": "Last game finances",
  "infra.stade.label": "Stands",
  "infra.stade.desc": "Increases how many spectators you can host",
  "infra.confort.label": "Comfort",
  "infra.confort.desc": "Seating and sightlines: brings spectators back",
  "infra.buvette.label": "Refreshments",
  "infra.buvette.desc": "Increases average spend per spectator",
  "infra.centre.label": "Training centre",
  "infra.centre.desc": "Speeds up every improvement from the coaching staff",
  "infra.pole.label": "Academy",
  "infra.pole.desc": "Regularly develops high-potential youngsters who join the squad directly — partly offsetting retirements",
  "infra.loges.label": "VIP boxes",
  "infra.loges.compte": {"un": "{n}/15 box", "autres": "{n}/15 boxes"},
  "infra.loges.recette": "{montant}/game in fixed income",
  "infra.loges.requis": "Box {n} requires {division}",
  "infra.loges.construire": "Build a box — {prix}",
  "poste.tous": "All positions",
  "poste.G": "Goalkeeper",
  "poste.D": "Defender",
  "poste.A": "Forward",
  "tri.ov": "Overall",
  "tri.tir": "Shot",
  "tri.def": "Def",
  "tri.vit": "Speed",
  "tri.gar": "Keeper",
  "tri.val": "Value",
  "tri.age": "Age",
  "tri.agr": "Aggression",
  "transferts.sousTitre": "Budget {budget} · {n} players under contract",
  "transferts.ferme": "The transfer market only opens from <b>season 2</b>.",
  "transferts.ferme.info": "Your first season is played with the starting squad — prove yourself, see who improves, and build your budget before entering the market.",
  "transferts.titre": "Recruitment centre",
  "transferts.info": "Budget available: {budgetHtml}. Buying = value +10% (± premium outside the division). Selling (Squad tab) = value −10%. A club may refuse to sell or counter with a higher price — a good <b>scout</b> limits that risk and lowers the price.<br>The badge next to the overall rating shows what the signing <b>adds</b>: the gap with the player in his position he would replace, that is the weakest in the group.<br>Below the value is his <b>wage per matchday</b> — the transfer fee is a one-off, the wage is paid every game for the whole contract.",
  "transferts.portee": "Scope:",
  "transferts.portee.division": "My division ({division})",
  "transferts.portee.pyramide": "The whole pyramid (outside the division)",
  "transferts.poste": "Position:",
  "transferts.trier": "Sort by:",
  "transferts.decroissant": "Descending",
  "transferts.croissant": "Ascending",
  "transferts.acheter": "Buy {prix}",
  "transferts.recruter": "Sign {prix}",
  "transferts.nonVendable": "not for sale",
  "transferts.aucun": "No player matches this filter.",

  // ---- rapport de match, sous-menu, objectifs
  "objectif.milieu": "Aim for mid-table",
  "objectif.titre": "Aim for the playoff title",
  "objectif.playoffs": "Reach the playoffs (Top 8)",
  "objectif.maintien": "Stay up",
  "objectif.maintienDescente": "Stay up (avoid relegation)",
  "rapport.titre": "Matchday {n} — Match report",
  "rapport.prolongation": "Level at the end of regulation — golden goal in overtime.",
  "rapport.autres": "Other results:",
  "rapport.recette": "Game revenue: {montantHtml} (details in the Club tab)",
  "rapport.aucunePenalite": "No penalties called.",
  "rapport.aucunBut": "No goals…",
  "intro.objectif": "The board's target for this season: {objectifHtml}.",

  // ---- fautes, coupe, palmarès, messages
  "faute.retenir": "holding",
  "faute.accrocher": "hooking",
  "faute.trebucher": "tripping",
  "faute.obstruction": "interference",
  "faute.cinglage": "slashing",
  "faute.crosseHaute": "high stick",
  "faute.piquage": "spearing",
  "faute.retardJeu": "delay of game",
  "faute.surnombre": "too many players",
  "faute.chargeViolente": "charging",
  "faute.dureteExcessive": "roughing",
  "faute.chargeBalustrade": "boarding",
  "faute.chargeCrosse": "cross-checking",
  "faute.cinglageBlessure": "slashing causing injury",
  "faute.antisportive": "unsportsmanlike conduct",
  "faute.contestation": "dissent",
  "faute.conduiteAntisportive": "misconduct",
  "faute.blessureIntentionnelle": "intent to injure",
  "faute.agression": "physical assault",
  "faute.coupCrosseTete": "dangerous stick blow to the head",
  "penalite.mineure": "Minor penalty",
  "penalite.majeure": "Major penalty",
  "penalite.mec": "Misconduct penalty (no shorthanded play, player replaced)",
  "penalite.pm": "Match penalty — sent off",
  "penalite.inferiorite": "{n}' shorthanded.",
  "coupe.nom": "Coupe de France",
  "coupe.tour.finale": "Final",
  "coupe.tour.demi": "Semi-final",
  "coupe.tour.quart": "Quarter-final",
  "coupe.tour.seizieme": "Round of 32",
  "coupe.tour.trentedeuxieme": "Round of 64",
  "coupe.tour.preliminaire": "Preliminary round",
  "coupe.presentation": "A knockout competition featuring <b>every team from every national division</b>, from N3 to Élite — your whole division (its real standings this season), plus the others generated for the occasion. The top seeds get a bye in the preliminary round. No draws possible.",
  "coupe.rythme": "Rounds unlock gradually across the league matchdays — the cup always finishes well before the playoff semi-finals.",
  "coupe.tirageVerrouille": "The draw becomes available from matchday {journee} (currently matchday {actuelle}).",
  "coupe.lancerTirage": "Make the draw",
  "coupe.aJouer": "to play",
  "coupe.prolongationCourte": "(OT)",
  "coupe.exemptes": "Seeds with a bye in the preliminary round:",
  "coupe.enCours": "in progress",
  "coupe.engagees": "{n} teams entered, from N3 to Élite.",
  "coupe.vainqueur": "Winner:",
  "coupe.resultatFinal": "See the final result",
  "coupe.tourVerrouille": "The next round becomes available from matchday {journee} (currently matchday {actuelle}).",
  "coupe.jouerProchain": "Play the next tie",
  "palmares.montee": "Promoted",
  "palmares.descente": "Relegated",
  "palmares.maintien": "Stayed up",
  "palmares.champion": "champions",
  "palmares.finaliste": "runners-up",
  "palmares.saisons": {"un": "{n} season", "autres": "{n} seasons"},
  "palmares.montees": {"un": "{n} promotion", "autres": "{n} promotions"},
  "palmares.saisonEnCours": "Season {n} under way",
  "palmares.vide.titre": "Your first season is under way",
  "palmares.vide.note": "The honours list fills up at the end of each season. Here is what will go in it.",
  "palmares.vide.classement": "<b>Final position</b> — where you finished in the regular season",
  "palmares.vide.playoffs": "<b>Playoffs</b> — how far you went",
  "palmares.vide.mouvement": "<b>Movement</b> — promoted, stayed up or relegated",
  "palmares.vide.buteur": "<b>Top scorer</b> — the one who carried the season",
  "messages.compte": {"un": "{n} message", "autres": "{n} messages"},
  "messages.nonLus": {"un": "{n} unread", "autres": "{n} unread"},
  "messages.boiteVide": "Inbox empty",
  "messages.vide.titre": "No messages yet",
  "messages.vide.note": "The board, the staff and other clubs will write to you as the season goes on.",
  "messages.vide.objectifs": "<b>Targets</b> — what the board expects of you",
  "messages.vide.blessures": "<b>Injuries</b> — who is out, and for how long",
  "messages.vide.contrats": "<b>Contracts</b> — expiries to plan for",
  "messages.vide.sponsors": "<b>Sponsors</b> — the offers that unlock",

  // ---- tutoriel guidé
  "tuto.passer": "Skip ⏭",
  "tuto.continuer": "Continue",
  "tuto.commencer": "Start",
  "tuto.compris": "Got it",
  "tuto.terminer": "Finish",
  "tuto.aller": "Tap the <b>{ecran}</b> tab in the bottom bar.",
  "tuto.tour.titre": "A quick look around",
  "tuto.tour.texte": "I will walk you through the screens one by one, up to your first game. It is short, and you can skip whenever you like.",
  "tuto.effectif.texte": "You are already here: this is your team sheet. You pick your keeper and your outfield players, and you see who is in form.",
  "tuto.composer.titre": "Picking your team",
  "tuto.composer.texte": "One keeper and four outfield players on the court, as roller in line hockey demands. The others rotate: the more you rotate, the less your players wear down.",
  "tuto.entrainement.texte": "Tap the <b>{ecran}</b> tab in the bottom bar. This is where your squad improves — or stalls, if nobody is there to coach it.",
  "tuto.coach.titre": "Your first coach",
  "tuto.coach.texte": "Tap <b>Hire</b> under a coach. With no staff there is <b>no progression</b> at all — the session is refused. I am showing you the cheapest, but you may pick another.",
  "tuto.seance.titre": "The first session",
  "tuto.seance.texte": "Tap <b>Run the session</b>. One per week, between matchdays — the players you <b>rested</b> benefit most, they turn up fresh.",
  "tuto.lireClassement.titre": "Reading the table",
  "tuto.lireClassement.texte": "FFRS scale: <b>3</b> points for a win, <b>2</b> for an overtime win, <b>1</b> for an overtime loss, <b>0</b> for a defeat. Level on points, goal difference decides.",
  "tuto.construire.titre": "Building your club",
  "tuto.construire.texte": "Stands, comfort, refreshments, training centre, sponsors. Careful: <b>going up a division requires a rated venue</b> — without the building work, promotion is denied even if you win. Two projects a season, no more.",
  "tuto.reste.titre": "Everything else",
  "tuto.reste.tiroir": "Tap <b>{plus}</b>, at the far right of the bottom bar: transfers, fixtures, Coupe de France, messages, history, help and settings live there.",
  "tuto.reste.large": "Your screen is wide: every screen fits in the bar — transfers, fixtures, Coupe de France, messages, history, help and settings. On a phone, the last ones move into a « More » drawer.",
  "tuto.tiroir.titre": "Close the drawer",
  "tuto.tiroir.texte": "Close the drawer: pull the handle down, or tap anywhere above the panel.",
  "tuto.jouer.titre": "Off you go",
  "tuto.jouer.texte": "Tap the <b>{bouton}</b> button at the bottom of the screen. You can watch the match unfold, or skip straight to the result.",
  "tuto.fin.titre": "Over to you!",
  "tuto.fin.texte": "You have everything you need: pick, train, build, recruit. Start in Régional and climb as high as you can — Élite is five divisions up.",

  // ---- écran Aide
  "aide.principe.titre": "How it works",
  "aide.principe.corps": "You are the player-manager of {clubHtml}, a roller hockey club (inline skates) starting in Régional, right at the bottom of the pyramid. Your goal: manage the squad, the finances and the staff to climb the 6 tiers — Régional → Pré-Nationale → N3 → N2 → N1 → Élite — season after season.",
  "aide.saison.titre": "▶ Playing through a season",
  "aide.saison.corps": "The big button at the top right moves the game on. It plays one league matchday at a time (home and away; the number of matchdays depends on how many teams are in the division). Your game is shown in <b>2D live</b>; the others are settled behind the scenes. At the end of the regular season, the <b>top 8</b> play the playoffs (quarters, semis, final — best-of-3 series, shown as a bracket in the Standings tab). The <b>2 finalists go up</b>, the <b>bottom 2 in the table go down</b> (except in Régional, the floor of the pyramid). Once your team is out of the playoffs, the button settles the rest of the bracket instantly — no need to play out other people's games.",
  "aide.coupe1.titre": "🏆 Coupe de France",
  "aide.coupe1.corps": "Every division takes part, from <b>Régional</b> to Élite: in your very first season you can draw a big club. And as in real life, when two clubs from different levels meet, <b>the smaller one hosts</b>.",
  "aide.effectif.titre": "👥 Squad",
  "aide.effectif.corps": "Your team has 14 players. Each has visible ratings (<b>Shot</b>, <b>Defence</b>, <b>Speed</b>, <b>Keeper</b>, <b>Aggression</b>) and career information: <b>Morale</b> (drops if he sits on the bench or the team loses), <b>Potential</b> (a hidden ceiling on improvement, shown as stars ⭐), and <b>Contract</b> (years left — on expiry the player extends or leaves on a free depending on his morale). You field <b>1 keeper + 4 to 8 outfield players</b> in rotation — picking 8 leaves a full line of 4 rested. <b>Injured</b> players (🤕) recover over time (faster with a doctor). Each season ages the squad by a year; players stay competitive far longer than elsewhere, but must leave the national league at <b>46</b> (48 for a keeper) to carry on quietly at regional level (not simulated) — a message then sums up their career at the club.",
  "aide.tactique.titre": "📋 Tactical instructions & personal targets",
  "aide.tactique.corps": "Pick a style (attacking / balanced / defensive) and a pressing level (high / medium / low): it genuinely affects match simulation and the number of penalties conceded. You can also change it live during a game (it applies from the next one, since the game shown has already been played). Each season, your 2 best shooters get a personal goal target, assessed at the end of the season (it affects their morale).",
  "aide.club.titre": "🏟️ Club & finances",
  "aide.club.corps": "Income from each home game: <b>ticketing</b> (adjustable price — careful, price sensitivity depends on your division and your position), <b>refreshments</b>, <b>VIP boxes</b>, <b>cumulative sponsorship</b> and <b>broadcast rights</b>. Recurring costs: the <b>players' wage bill</b> and <b>staff wages</b>, paid every matchday. Upgrade your facilities (stands, comfort, refreshments, training centre) — <b>at most 2 projects a season</b>; building takes time, you cannot modernise everything at once.",
  "aide.staff.titre": "🎯 Coaching staff & training",
  "aide.staff.corps": "8 posts on the <b>market</b>: attack, defence, fitness, goalkeeping, discipline (these improve ratings), plus a <b>special teams coach</b> (strengthens power plays and penalty kills), a <b>scout</b> (cuts transfer fees) and a <b>doctor</b> (reduces the risk and length of injuries). Replace a coach directly with a better one (severance included) or <b>train</b> him to raise his rating. One <b>non-matchday training session</b> a week mostly benefits the players left out.",
  "aide.transferts.titre": "💰 Transfers",
  "aide.transferts.corps": "The recruitment centre lists players from your division <b>or from the whole pyramid</b> (recruiting outside the division, with a premium if you poach from a higher one). Filter by position, sort by any rating. A club may <b>refuse to sell</b> or <b>counter with a higher price</b> — a good scout limits that risk. You can also <b>loan out</b> a player for the season (he comes back in the off-season, slightly improved) rather than sell him.",
  "aide.direct.titre": "🏒 The live game",
  "aide.direct.corps": "The 4 outfield players shown are your best Shot (forwards) and Defence (defenders). They play real tactics: zone defence protecting the <b>slot</b> (the dangerous area in front of the net), pressing, finding space and cutting to goal. The puck has real physics (possession, passes, visible shots, rebounds). <b>No body checking</b> — it is a foul in roller hockey. After every goal, players line up for the face-off before play resumes. Set the speed (x1/x2/x4) or skip straight to the report.",
  "aide.penalites.titre": "🟨 Penalties (FFRS rules)",
  "aide.penalites.corps": "<b>Minor (2')</b>: shorthanded, cancelled if you concede. <b>Major (5')</b>: shorthanded, does not cancel. <b>Misconduct (10')</b>: player in the box but replaced, no shorthanded play. <b>Match penalty</b>: sent off. 3 minors for the same player = automatic misconduct. An aggressive team takes more penalties.",
  "aide.coupe2.titre": "🏆 Coupe de France",
  "aide.coupe2.corps": "A knockout side competition (Cup tab): your team, a rival from your division, and 2 representatives from each of the other 3 divisions — 8 teams, 3 rounds, no draws. Make the draw whenever you like during the season. Once you are out, the rest is settled instantly.",
  "aide.direction.titre": "📋 Board, inbox & history",
  "aide.direction.corps": "Each season the board sets a <b>target</b> (visible at all times at the top of the screen, with its <b>confidence</b> out of 100) — meeting it earns a bonus, missing it lowers confidence. The <b>inbox</b> (Messages tab) gathers all the news: targets, expiring contracts, cup results and so on. The <b>History</b> tab archives the table, the playoffs and the top scorer of each completed season.",
  "aide.sauvegarde.titre": "💾 Saving",
  "aide.sauvegarde.corps": "The game lives in memory. Go to the <b>Save</b> tab to download your progress as a .json file and load it back later. Remember to save before closing the page!",
  "aide.titre": "Game guide",
  "aide.sousTitre": "The rules, the mechanics, the shortcuts",

  // ---- introduction et résumé de saison
  "modale.passer": "Skip",
  "modale.toutPasser": "Skip all",
  "modale.suivantReste": "Next · {n}",
  "intro.bienvenue": "Welcome to the club",
  "intro.division": "Division",
  "intro.plancher": "You start at the bottom of the pyramid, like everyone else.",
  "intro.connaissance": "Let us get to know your players first.",
  "intro.voirEffectif": "See the squad",
  "intro.tonEffectif": "Your squad",
  "intro.age": {"un": "{n} year old", "autres": "{n} years old"},
  "intro.salaire": "Wage",
  "intro.joueurSurTotal": "Player {rang} of {total}",
  "club.niveauCourt": "level {n}",
  "resume.matchsJoues": {"un": "{n} game played", "autres": "{n} games played"},
  "resume.sur": "of {n}",
  "resume.parcours": "The campaign",
  "resume.victoires": "Wins",
  "resume.defaites": "Defeats",
  "resume.enProl": "+{n} in OT",
  "resume.butsMarques": "Goals for",
  "resume.butsEncaisses": "Goals against",
  "resume.hommes": "Players of the season",
  "resume.meilleurButeur": "Club top scorer",
  "resume.buts": {"un": "goal", "autres": "goals"},
  "resume.aucunButeur": "No scorer this season — you will need to find answers up front.",
  "resume.butsEquipe": "Team goals",
  "resume.comptes": "The books",
  "resume.prime": "Placement bonus",
  "resume.forceMoyenne": "Average rating",
  "resume.niveauDivision": "Division level",
  "resume.evolutions": "Changes will show from next season onwards.",
  "resume.voirBilan": "See the review",
  "modale.suivantEnAttente": "Next · {n} waiting",
  "modale.fermer": "Close",
  "resume.saisonTitre": "Season {annees}",

  // ---- modales, toasts et confirmations
  "dlg.effacer.titre": "Delete this slot",
  "dlg.effacer.ok": "Delete",
  "dlg.effacer.texte": "Permanently delete {quoi}?",
  "toast.emplacementEfface": "Slot deleted.",
  "toast.aucuneSauvegarde": "No saved game in this slot.",
  "toast.saisonTerminee": "The season is over — start the next one from the Standings tab.",
  "toast.budgetIndemnite": "Not enough budget to pay the severance.",
  "toast.coachPlafond": "This coach has reached his skill ceiling.",
  "toast.seanceDeja": "Session already held this week — the next one becomes available after the next game.",
  "toast.seanceSansGain": "Session over — no improvement this time.",
  "toast.blesseNonPrete": "An injured player cannot be loaned out.",
  "toast.effectifTropCourt": "You need to keep enough players to loan this one out.",
  "toast.barreVide": "You must keep at least one screen in the bar.",
  "toast.coupeTerminee": "This season's Coupe de France is over.",
  "toast.sauvegardeChargee": "Save loaded!",
  "toast.niveauExige": "Level {n} requires playing at least in {division}.",
  "toast.logeExige": "VIP box {n} requires playing at least in {division}.",
  "toast.prerequis": "Requirements not met for {quoi}: {detail}.",
  "toast.marcheFerme": "The transfer market only opens from season 2.",
  "toast.refuseVendre": "{club} flatly refuses to sell {nom}.",
  "toast.refusePartir": "{club} flatly refuses to let {nom} go.",
  "toast.blesse": {"un": "{nom} is injured — {n} matchday until he returns.", "autres": "{nom} is injured — {n} matchdays until he returns."},
  "toast.tirageCoupe": "The cup draw becomes available from matchday {n}.",
  "toast.tourCoupe": "This cup round unlocks on matchday {n} (currently {actuelle}).",
  "toast.consigneOn": "{nom} is under orders to play safe: fewer fouls, less output.",
  "toast.consigneOff": "{nom} is free to play his game again.",
  "dlg.loge.ok": "Build",
  "dlg.loge.texte": "Build one more VIP box for {prix}?",
  "dlg.sponsor.titre": "Terminate a sponsorship",
  "dlg.sponsor.texte": "Terminate the contract with {nom}?\\n\\nYou lose {montant} per game.",
  "dlg.licencier.titre": "Dismiss",
  "dlg.licencier.texte": "Dismiss {nom}?\\n\\nSeverance: {montant}. He will return to the market.",
  "dlg.pret.titre": "Loan out a player",
  "dlg.pret.texte": "Loan {nom} out for the rest of the season?\\n\\nHe will be back in the off-season, with a bit more experience.",
  "dlg.nouvelle.titre": "New game",
  "dlg.nouvelle.ok": "Overwrite and continue",
  "dlg.nouvelle.texte": "A game is already under way.\\n\\nStarting a new game will permanently erase the autosave. Export it first if you want to keep it.",
  "dlg.fichierInvalide.titre": "Invalid file",
  "dlg.fichierInvalide.texte": "This file is not a usable Roller Hockey Manager save.\\n\\nTechnical detail: {detail}",
  "dlg.exportImpossible.titre": "Export failed",
  "dlg.exportImpossible.texte": "The save could not be exported.\\n\\nTechnical detail: {detail}",
  "dlg.exportOk.titre": "Save exported",
  "dlg.exportOk.texte": "The file was written here:\\n\\n{chemin}",

  // ---- fin de saison, écran titre, dialogues
  "fin.titre": "End of season {annees}",
  "fin.champion": "{division} playoff champions",
  "fin.primeTitre": "Title bonus: {montant}.",
  "fin.finaliste": "{division} playoff runners-up",
  "fin.finaliste.note": "Beaten in the final, but a good season all the same.",
  "fin.score": "Score: {mes} — {ses}{prol}.",
  "fin.apresProlongation": " after overtime",
  "fin.barrage.maintien": "Play-off won — you stay in Élite",
  "fin.barrage.descente": "Play-off lost — relegated to Nationale 1",
  "fin.barrage.recevait": "9th in the qualifying phase, you hosted {adversaire}, 2nd in Nationale 1.",
  "fin.barrage.montee": "Play-off won — promoted to Élite",
  "fin.barrage.maintienN1": "Play-off lost — you stay in Nationale 1",
  "fin.barrage.deplacait": "As playoff runners-up you travelled to {adversaire}, 9th in Élite — the rules give home advantage to the Élite club.",
  "fin.playdown.maintien": "Play-down won — you stay in Nationale 1",
  "fin.playdown.descente": "Play-down lost — relegated to Nationale 2",
  "fin.playdown.recevait": "{rang}th in the group, you hosted {adversaire}.",
  "fin.playdown.deplacait": "{rang}th in the group, you travelled to {adversaire}.",
  "fin.montee": "Promoted to {division}",
  "fin.montee.detail": "Promotion cheque: {montant}. The squad improves to cope with the level above.",
  "fin.montee.refusee": "Promotion denied — venue not rated",
  "fin.montee.refusee.detail": "On the court, promotion to {division} was earned. But that division requires a <b>class {classe}</b> venue, meaning a level {requis} ground: yours is level {niveau}. Do the building work, and the place is yours.",
  "fin.descente": "Relegated to {division}",
  "fin.descente.division": "{rang}<sup>th</sup> of {total} in the division table: the bottom {quota} go down. It was not your group that condemned you, it was the division as a whole.",
  "fin.descente.simple": "You will have to climb back next season.",
  "fin.bilanRegulier": "Regular season review",
  "fin.quitteClub": {"un": "He leaves the club after {n} game in a {club} shirt.", "autres": "He leaves the club after {n} games in a {club} shirt."},
  "menu.sousTitre": "Take a club at the bottom of the pyramid and carry it up to Élite.",
  "menu.slot.libre": "Slot {n} — empty",
  "menu.slot.illisible": "Slot {n} — unreadable save",
  "menu.slot.illisible.detail": "{n} unreadable bytes — tap to find out more, or delete it",
  "menu.slot.detail": "season {saison}, matchday {journee}",
  "menu.slot.demarrer": "Start a new game here",
  "menu.charger": "Load a save",
  "menu.charger.detail": "From a .json file",
  "menu.pied.ok": "The game is saved automatically in this browser. Remember to export a file from the Save tab to keep it elsewhere.",
  "menu.pied.bloque": "This browser blocks local storage: Continue is unavailable. Use file export/import from the Save tab.",
  "dlg.illisible.emplacement": "Slot {n} contains a save that could not be read.\\n\\nTechnical detail: {erreur} ({octets} bytes)\\n\\nIt is corrupted, or comes from too old a version. It has not been deleted: you can delete it from the menu, or play in another slot.",
  "dlg.illisible.auto": "The autosave could not be read. It may be corrupted or come from too old a version.\\n\\nTechnical detail: {detail}",
  "dlg.menu.titre": "Back to menu",
  "dlg.menu.ok": "Back to menu",
  "dlg.menu.texteLong": "Go back to the main menu?\\n\\nThe game stays saved automatically. Remember to export it from the Save tab if you want to keep it elsewhere.",
  "dlg.menu.texteCourt": "Go back to the main menu?\\n\\nThe game is saved.",
  "stade.chiffrage.pret": "We already have enough to pay for the next tier ({montant}): it is simply a decision now.",
  "stade.chiffrage.rien": "The next tier costs {montant}, and we are making nothing this season. We need to find revenue.",
  "stade.chiffrage.epargne": {"un": "The next tier costs {montant}: <b>{n} season of saving</b> at the current rate.", "autres": "The next tier costs {montant}: <b>{n} seasons of saving</b> at the current rate."},

  // ---- direct, entraînement, séries
  "direct.ambiance.0": "A fine stick battle along the boards.",
  "direct.ambiance.1": "The keeper blocks it with the blocker.",
  "direct.ambiance.2": "Pass from behind the net, the play is flowing.",
  "direct.ambiance.3": "Shot sliced wide, the stick rattled.",
  "direct.ambiance.4": "Won back at the face-off circle.",
  "direct.ambiance.5": "Quick counter, they are flying!",
  "direct.ambiance.6": "Strong puck protection in the corner.",
  "direct.ambiance.7": "Slap shot... over the net!",
  "direct.ambiance.8": "Fine interception in man-to-man marking.",
  "entrainement.gain": "{nom}: {signe} {stat} ({valeur})",
  "playoffs.serie.quart": "Quarter-final {n}",
  "playoffs.serie.demi": "Semi-final {n}",
  "playoffs.serie.finale": "Final",
  "playoffs.mene": "{meneur} lead {a}-{b} against {adversaire}",
  "playoffs.match": "game {n}",
  "playoffs.serieRemportee": "(series won)",
  "direct.prolongation": "Overtime — sudden death.",
  "direct.finMatch": "Full time!",
  "direct.scoreFinal": "Final score {a} — {b}."
});

if (typeof PIECES_CHARGEES === 'object') PIECES_CHARGEES.textesen = true;
